<Project Sdk="Microsoft.NET.Sdk.Web">

    <PropertyGroup>
        <TargetFramework>net10.0</TargetFramework>
        <Nullable>enable</Nullable>
        <ImplicitUsings>enable</ImplicitUsings>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="Microsoft.AspNetCore.OpenApi" Version="9.0.2"/>
        <PackageReference Include="NotMediator" Version="1.0.5"/>
        <PackageReference Include="Npgsql" Version="10.0.1" />
        <PackageReference Include="Npgsql.EntityFrameworkCore.PostgreSQL" Version="10.0.0" />
        <PackageReference Include="Scalar.AspNetCore" Version="2.13.3"/>
    </ItemGroup>

    <ItemGroup>
        <Folder Include="ActionFilter\"/>
        <Folder Include="EventBus\"/>
        <Folder Include="Extensions\"/>
        <Folder Include="ReponseEntity\"/>
    </ItemGroup>

    <ItemGroup>
        <ProjectReference Include="..\FileDev.Domain\FileDev.Domain.csproj"/>
        <ProjectReference Include="..\FileDev.Infrastructure\FileDev.Infrastructure.csproj" />
        <ProjectReference Include="..\NotBlog.ServiceDefaults\NotBlog.ServiceDefaults.csproj" />
    </ItemGroup>

</Project>
