<Project Sdk="Microsoft.NET.Sdk.Web">

    <PropertyGroup>
        <TargetFramework>net10.0</TargetFramework>
        <Nullable>enable</Nullable>
        <ImplicitUsings>enable</ImplicitUsings>
    </PropertyGroup>

    <ItemGroup>
        <Protobuf Include="Protos\filestorage.proto" GrpcServices="Server" />
    </ItemGroup>

    <ItemGroup>
       
        <PackageReference Include="Aspire.RabbitMQ.Client" Version="13.4.6" />
        
        <PackageReference Include="Aspire.StackExchange.Redis.DistributedCaching" Version="13.4.6" />
        
        <PackageReference Include="Grpc.AspNetCore" Version="2.80.0" />
        
        <PackageReference Include="Grpc.Tools" Version="2.83.0">
          <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
          <PrivateAssets>all</PrivateAssets>
        </PackageReference>
        <PackageReference Include="Microsoft.AspNetCore.OpenApi" Version="10.0.9" />
        <PackageReference Include="Microsoft.OpenApi" Version="2.7.5" />
        <PackageReference Include="Microsoft.AspNetCore.SignalR.StackExchangeRedis" Version="10.0.9" />
        <PackageReference Include="Microsoft.EntityFrameworkCore.Design" Version="10.0.9">
          <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
          <PrivateAssets>all</PrivateAssets>
        </PackageReference>
        <PackageReference Include="Microsoft.Extensions.Caching.StackExchangeRedis" Version="10.0.9" />
        <PackageReference Include="NotMediator" Version="1.0.5" />
        <PackageReference Include="Npgsql" Version="10.0.3" />
        <PackageReference Include="Npgsql.EntityFrameworkCore.PostgreSQL" Version="10.0.2" />
        <PackageReference Include="Scalar.AspNetCore" Version="2.16.4" />
        <PackageReference Include="StackExchange.Redis" Version="3.1.0" />
    </ItemGroup>

    <ItemGroup>
        <ProjectReference Include="..\CacheMemory\CacheMemory.csproj" />
        <ProjectReference Include="..\EventBus\EventBus.csproj" />
        <ProjectReference Include="..\FileDev.Domain\FileDev.Domain.csproj" />
        <ProjectReference Include="..\FileDev.Infrastructure\FileDev.Infrastructure.csproj" />
        <ProjectReference Include="..\JWToken\JWToken.csproj" />
        <ProjectReference Include="..\NotBlog.ServiceDefaults\NotBlog.ServiceDefaults.csproj" />
    </ItemGroup>

</Project>
