<Project Sdk="Microsoft.NET.Sdk.Web">

    <PropertyGroup>
        <TargetFramework>net10.0</TargetFramework>
        <Nullable>enable</Nullable>
        <ImplicitUsings>enable</ImplicitUsings>
    </PropertyGroup>

    <ItemGroup>
        <Compile Remove="Protos\**"/>
    </ItemGroup>

    <ItemGroup>
        <EmbeddedResource Remove="Protos\**"/>
    </ItemGroup>

    <ItemGroup>
        <Content Remove="Protos\**"/>
    </ItemGroup>

    <ItemGroup>
        <None Remove="Protos\**"/>
    </ItemGroup>

    <ItemGroup>
        <ProjectReference Include="..\Markdown.Domain\Markdown.Domain.csproj"/>
        <ProjectReference Include="..\Markdown.Infrastructure\Markdown.Infrastructure.csproj" />
        <ProjectReference Include="..\NotBlog.ServiceDefaults\NotBlog.ServiceDefaults.csproj" />
        <ProjectReference Include="..\Evenbus\Evenbus.csproj"/>
    </ItemGroup>

    <ItemGroup>
        <PackageReference Include="Aspire.RabbitMQ.Client" Version="13.4.6"/>
        <PackageReference Include="Microsoft.AspNetCore.Mvc.Core" Version="2.3.11"/>
        <PackageReference Include="Microsoft.AspNetCore.OpenApi" Version="10.0.9"/>
        <PackageReference Include="NotMediator" Version="1.0.5" />
        <PackageReference Include="Npgsql.EntityFrameworkCore.PostgreSQL" Version="10.0.2"/>
        <PackageReference Include="Scalar.AspNetCore" Version="2.16.4"/>
    </ItemGroup>

    <ItemGroup>
        <Folder Include="ActionFilter\"/>
      <Folder Include="EventBus\" />
    </ItemGroup>

</Project>
