<Project Sdk="Microsoft.NET.Sdk.Web">

    <PropertyGroup>
        <TargetFramework>net10.0</TargetFramework>
        <Nullable>enable</Nullable>
        <ImplicitUsings>enable</ImplicitUsings>
    </PropertyGroup>

    <ItemGroup>
        <Compile Remove="Protos\**" />
    </ItemGroup>

    <ItemGroup>
        <EmbeddedResource Remove="Protos\**" />
    </ItemGroup>

    <ItemGroup>
        <Content Remove="Protos\**" />
    </ItemGroup>

    <ItemGroup>
        <None Remove="Protos\**" />
    </ItemGroup>

    <ItemGroup>
        <ProjectReference Include="..\Markdown.Domain\Markdown.Domain.csproj" />
        <ProjectReference Include="..\Markdown.Infrastructure\Markdown.Infrastructure.csproj" />
        <ProjectReference Include="..\NotBlog.ServiceDefaults\NotBlog.ServiceDefaults.csproj" />
        <ProjectReference Include="..\JWToken\JWToken.csproj" />
        <ProjectReference Include="..\Eventbus\EventBus.csproj" />
        <ProjectReference Include="..\Commons\Commons.csproj" />
    </ItemGroup>

    <ItemGroup>
        <PackageReference Include="Aspire.Npgsql.EntityFrameworkCore.PostgreSQL" Version="13.4.6" />
        <PackageReference Include="Microsoft.AspNetCore.Authentication.JwtBearer" Version="10.0.11" />
        <PackageReference Include="Aspire.RabbitMQ.Client" Version="13.4.6" />
        <PackageReference Include="Microsoft.AspNetCore.OpenApi" Version="10.0.11" />
        <PackageReference Include="NotMediator" Version="2.0.1" />
        <PackageReference Include="Microsoft.EntityFrameworkCore.Design" Version="10.0.11">
            <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
            <PrivateAssets>all</PrivateAssets>
        </PackageReference>
        <PackageReference Include="Npgsql.EntityFrameworkCore.PostgreSQL" Version="10.0.3" />
        <PackageReference Include="Scalar.AspNetCore" Version="2.16.20" />
    </ItemGroup>

</Project>
