// <auto-generated />
using System;
using System.Collections.Generic;
using FileDev.Infrastructres.DbContext;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace FileDev.Infrastructres.Migrations
{
    [DbContext(typeof(FileDbContext))]
    [Migration("20250919040347_initialCreate")]
    partial class initialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("FileDev.Domain.DomainEntities.FileGroup", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreateTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("FileGroupName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.PrimitiveCollection<List<string>>("FileGroupTags")
                        .HasColumnType("text[]");

                    b.Property<int>("FileSafety")
                        .HasColumnType("integer");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<string>("MaterializedPath")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid?>("ParentId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("RepositoryGuid")
                        .HasColumnType("uuid");

                    b.Property<Guid>("UserGuid")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("ParentId");

                    b.HasIndex("RepositoryGuid");

                    b.ToTable("FileGroup");
                });

            modelBuilder.Entity("FileDev.Domain.DomainEntities.NotFile", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("FileDescription")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("FileGroupGuid")
                        .HasColumnType("uuid");

                    b.Property<string>("FileHash")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("FileSafety")
                        .HasColumnType("integer");

                    b.Property<double>("FileSize")
                        .HasColumnType("double precision");

                    b.Property<string>("FileType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("UserGuid")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("FileGroupGuid");

                    b.ToTable("NotFile", (string)null);
                });

            modelBuilder.Entity("FileDev.Domain.DomainEntities.NotFileRepository", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<long>("FileCount")
                        .HasColumnType("bigint");

                    b.Property<int>("FileSafety")
                        .HasColumnType("integer");

                    b.Property<DateTime>("LastModified")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("NotFileRepositoryName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("RepositoryBrief")
                        .HasColumnType("text");

                    b.Property<string>("RepositoryCover")
                        .HasColumnType("text");

                    b.Property<Guid>("UserGuid")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.ToTable("NotFileRepository", (string)null);
                });

            modelBuilder.Entity("FileDev.Domain.DomainEntities.FileGroup", b =>
                {
                    b.HasOne("FileDev.Domain.DomainEntities.FileGroup", "Parent")
                        .WithMany("ChildredFileGroup")
                        .HasForeignKey("ParentId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("FileDev.Domain.DomainEntities.NotFileRepository", null)
                        .WithMany("FileGroups")
                        .HasForeignKey("RepositoryGuid")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Parent");
                });

            modelBuilder.Entity("FileDev.Domain.DomainEntities.NotFile", b =>
                {
                    b.HasOne("FileDev.Domain.DomainEntities.FileGroup", null)
                        .WithMany("Files")
                        .HasForeignKey("FileGroupGuid")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.OwnsOne("FileDev.Domain.DomainEntities.ObjectMap", "ObjectMap", b1 =>
                        {
                            b1.Property<Guid>("NotFileId")
                                .HasColumnType("uuid");

                            b1.Property<string>("ObjectKey")
                                .IsRequired()
                                .HasColumnType("varchar")
                                .HasColumnName("ObjectKey");

                            b1.Property<string>("PhysicalName")
                                .IsRequired()
                                .HasColumnType("varchar")
                                .HasColumnName("PhysicalName");

                            b1.HasKey("NotFileId");

                            b1.ToTable("NotFile");

                            b1.WithOwner()
                                .HasForeignKey("NotFileId");
                        });

                    b.Navigation("ObjectMap")
                        .IsRequired();
                });

            modelBuilder.Entity("FileDev.Domain.DomainEntities.FileGroup", b =>
                {
                    b.Navigation("ChildredFileGroup");

                    b.Navigation("Files");
                });

            modelBuilder.Entity("FileDev.Domain.DomainEntities.NotFileRepository", b =>
                {
                    b.Navigation("FileGroups");
                });
#pragma warning restore 612, 618
        }
    }
}
