services:
  docker-compose-dashboard:
    image: "mcr.microsoft.com/dotnet/aspire-dashboard"
    ports:
      - "18888:18888"
    expose:
      - "18889"
      - "18890"
    networks:
      - "aspire"
    restart: "always"
  postgres:
    image: "docker.io/library/postgres:18.3"
    environment:
      POSTGRES_HOST_AUTH_METHOD: "scram-sha-256"
      POSTGRES_INITDB_ARGS: "--auth-host=scram-sha-256 --auth-local=scram-sha-256"
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "${POSTGRES_PASSWORD}"
    expose:
      - "5432"
    volumes:
      - type: "volume"
        target: "/var/lib/postgresql"
        source: "notblog.apphost-4e335c671b-postgres-data"
        read_only: false
    networks:
      - "aspire"
    restart: "always"
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 10s
      timeout: 5s
      retries: 5
  redis:
    image: "docker.io/library/redis:8.6"
    command:
      - "-c"
      - "redis-server --requirepass $$REDIS_PASSWORD --save 60 1"
    entrypoint:
      - "/bin/sh"
    environment:
      REDIS_PASSWORD: "${REDIS_PASSWORD}"
    expose:
      - "6379"
    volumes:
      - type: "volume"
        target: "/data"
        source: "notblog.apphost-4e335c671b-Redis-data"
        read_only: false
    networks:
      - "aspire"
    restart: "always"
    healthcheck:
      test: [ "CMD-SHELL", "redis-cli -a $$REDIS_PASSWORD ping" ]
      interval: 10s
      timeout: 5s
      retries: 5
  eventbus:
    image: "docker.io/library/rabbitmq:4.3"
    environment:
      RABBITMQ_DEFAULT_USER: "guest"
      RABBITMQ_DEFAULT_PASS: "${EVENTBUS_PASSWORD}"
    expose:
      - "5672"
    volumes:
      - type: "volume"
        target: "/var/lib/rabbitmq"
        source: "notblog.apphost-4e335c671b-EventBus-data"
        read_only: false
    networks:
      - "aspire"
    restart: "always"
    healthcheck:
      test: [ "CMD", "rabbitmq-diagnostics", "ping" ]
      interval: 10s
      timeout: 5s
      retries: 5
  filedev-web-api:
    build:
      context: ../FileDev.Web.API
      dockerfile: Dockerfile
    depends_on:
      # ✅ 新增依赖
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy
      eventbus:
        condition: service_healthy
    environment:
      JWT_PRIVATE_KEY: "${JWT_PRIVATE_KEY}"
      OTEL_DOTNET_EXPERIMENTAL_OTLP_RETRY: "in_memory"
      ASPNETCORE_FORWARDEDHEADERS_ENABLED: "true"
      HTTP_PORTS: "${FILEDEV_WEB_API_PORT}"
      ConnectionStrings__NotFilePostgres: "Host=postgres;Port=5432;Username=postgres;Password=${POSTGRES_PASSWORD};Database=notfilepostgres;SSL Mode=Disable"
      NOTFILEPOSTGRES_HOST: "postgres"
      NOTFILEPOSTGRES_PORT: "5432"
      NOTFILEPOSTGRES_USERNAME: "postgres"
      NOTFILEPOSTGRES_PASSWORD: "${POSTGRES_PASSWORD}"
      NOTFILEPOSTGRES_URI: "postgresql://postgres:${POSTGRES_PASSWORD}@postgres:5432/notfilepostgres"
      NOTFILEPOSTGRES_JDBCCONNECTIONSTRING: "jdbc:postgresql://postgres:5432/notfilepostgres"
      NOTFILEPOSTGRES_DATABASENAME: "notfilepostgres"
      ConnectionStrings__CacheMemory: "redis:6379,password=${REDIS_PASSWORD}"
      CACHEMEMORY_HOST: "redis"
      CACHEMEMORY_PORT: "6379"
      CACHEMEMORY_PASSWORD: "${REDIS_PASSWORD}"
      CACHEMEMORY_URI: "redis://:${REDIS_PASSWORD}@redis:6379"
      ConnectionStrings__EventBus: "amqp://guest:${EVENTBUS_PASSWORD}@eventbus:5672"
      EVENTBUS_HOST: "eventbus"
      EVENTBUS_PORT: "5672"
      EVENTBUS_USERNAME: "guest"
      EVENTBUS_PASSWORD: "${EVENTBUS_PASSWORD}"
      EVENTBUS_URI: "amqp://guest:${EVENTBUS_PASSWORD}@eventbus:5672"
      DbContextConnect: "Host=postgres;Port=5432;Username=postgres;Password=${POSTGRES_PASSWORD};Database=notfilepostgres;SSL Mode=Disable"
      OTEL_EXPORTER_OTLP_ENDPOINT: "http://docker-compose-dashboard:18889"
      OTEL_EXPORTER_OTLP_PROTOCOL: "grpc"
      OTEL_SERVICE_NAME: "filedev-web-api"
    expose:
      - "${FILEDEV_WEB_API_PORT}"
    ports:
      - "${FILEDEV_WEB_API_PORT}:9093"
    networks:
      - "aspire"
  identity-web-api:
    build:
      context: ./Identity.Web.API
      dockerfile: Dockerfile
    depends_on:
      # ✅ 新增依赖
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy
      eventbus:
        condition: service_healthy
    environment:
      JWT_PRIVATE_KEY: "${JWT_PRIVATE_KEY}"
      OTEL_DOTNET_EXPERIMENTAL_OTLP_RETRY: "in_memory"
      ASPNETCORE_FORWARDEDHEADERS_ENABLED: "true"
      HTTP_PORTS: "${IDENTITY_WEB_API_PORT}"
      ConnectionStrings__IdentityPostgres: "Host=postgres;Port=5432;Username=postgres;Password=${POSTGRES_PASSWORD};Database=identitypostgres;SSL Mode=Disable"
      IDENTITYPOSTGRES_HOST: "postgres"
      IDENTITYPOSTGRES_PORT: "5432"
      IDENTITYPOSTGRES_USERNAME: "postgres"
      IDENTITYPOSTGRES_PASSWORD: "${POSTGRES_PASSWORD}"
      IDENTITYPOSTGRES_URI: "postgresql://postgres:${POSTGRES_PASSWORD}@postgres:5432/identitypostgres"
      IDENTITYPOSTGRES_JDBCCONNECTIONSTRING: "jdbc:postgresql://postgres:5432/identitypostgres"
      IDENTITYPOSTGRES_DATABASENAME: "identitypostgres"
      ConnectionStrings__Redis: "redis:6379,password=${REDIS_PASSWORD}"
      REDIS_HOST: "redis"
      REDIS_PORT: "6379"
      REDIS_PASSWORD: "${REDIS_PASSWORD}"
      REDIS_URI: "redis://:${REDIS_PASSWORD}@redis:6379"
      ConnectionStrings__EventBus: "amqp://guest:${EVENTBUS_PASSWORD}@eventbus:5672"
      EVENTBUS_HOST: "eventbus"
      EVENTBUS_PORT: "5672"
      EVENTBUS_USERNAME: "guest"
      EVENTBUS_PASSWORD: "${EVENTBUS_PASSWORD}"
      EVENTBUS_URI: "amqp://guest:${EVENTBUS_PASSWORD}@eventbus:5672"
      FILEDEV_WEB_API_HTTP: "http://filedev-web-api:${FILEDEV_WEB_API_PORT}"
      services__filedev-web-api__http__0: "http://filedev-web-api:${FILEDEV_WEB_API_PORT}"
      FILEDEV_WEB_API_HTTPS: "https://filedev-web-api:${FILEDEV_WEB_API_PORT}"
      FileStorageGrpc__Address: "https://filedev-web-api"
      DbContextOption__DbContextConnect: "Host=postgres;Port=5432;Username=postgres;Password=${POSTGRES_PASSWORD};Database=identitypostgres;SSL Mode=Disable"
      OTEL_EXPORTER_OTLP_ENDPOINT: "http://docker-compose-dashboard:18889"
      OTEL_EXPORTER_OTLP_PROTOCOL: "grpc"
      OTEL_SERVICE_NAME: "identity-web-api"
    expose:
      - "5052:${IDENTITY_WEB_API_PORT}"
    ports: -"${IDENTITY_WEB_API_PORT}:9091"
    networks:
      - "aspire"
  message-web-api:
    build:
      context: ./Message.Web.API
      dockerfile: Dockerfile
    depends_on:
      # ✅ 新增依赖
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy
      eventbus:
        condition: service_healthy
    environment:
      JWT_PRIVATE_KEY: "${JWT_PRIVATE_KEY}"
      OTEL_DOTNET_EXPERIMENTAL_OTLP_RETRY: "in_memory"
      ASPNETCORE_FORWARDEDHEADERS_ENABLED: "true"
      HTTP_PORTS: "${MESSAGE_WEB_API_PORT}"
      ConnectionStrings__PostgresSQL: "Host=postgres;Port=5432;Username=postgres;Password=${POSTGRES_PASSWORD};Database=messagepostgres;SSL Mode=Disable"
      POSTGRESSQL_HOST: "postgres"
      POSTGRESSQL_PORT: "5432"
      POSTGRESSQL_USERNAME: "postgres"
      POSTGRESSQL_PASSWORD: "${POSTGRES_PASSWORD}"
      POSTGRESSQL_URI: "postgresql://postgres:${POSTGRES_PASSWORD}@postgres:5432/messagepostgres"
      POSTGRESSQL_JDBCCONNECTIONSTRING: "jdbc:postgresql://postgres:5432/messagepostgres"
      POSTGRESSQL_DATABASENAME: "messagepostgres"
      ConnectionStrings__Redis: "redis:6379,password=${REDIS_PASSWORD}"
      REDIS_HOST: "redis"
      REDIS_PORT: "6379"
      REDIS_PASSWORD: "${REDIS_PASSWORD}"
      REDIS_URI: "redis://:${REDIS_PASSWORD}@redis:6379"
      ConnectionStrings__EventBus: "amqp://guest:${EVENTBUS_PASSWORD}@eventbus:5672"
      EVENTBUS_HOST: "eventbus"
      EVENTBUS_PORT: "5672"
      EVENTBUS_USERNAME: "guest"
      EVENTBUS_PASSWORD: "${EVENTBUS_PASSWORD}"
      EVENTBUS_URI: "amqp://guest:${EVENTBUS_PASSWORD}@eventbus:5672"
      FILEDEV_WEB_API_HTTP: "http://filedev-web-api:${FILEDEV_WEB_API_PORT}"
      services__filedev-web-api__http__0: "http://filedev-web-api:${FILEDEV_WEB_API_PORT}"
      FILEDEV_WEB_API_HTTPS: "https://filedev-web-api:${FILEDEV_WEB_API_PORT}"
      OTEL_EXPORTER_OTLP_ENDPOINT: "http://docker-compose-dashboard:18889"
      OTEL_EXPORTER_OTLP_PROTOCOL: "grpc"
      OTEL_SERVICE_NAME: "message-web-api"
    expose:
      - "${MESSAGE_WEB_API_PORT}"
    ports: 
      - "${MESSAGE_WEB_API_PORT}:9092"
    networks:
      - "aspire"
  markdown-web-api:
    build:
      context: ./Markdown.Web.API
      dockerfile: Dockerfile
    depends_on:
      # ✅ 新增依赖
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy
      eventbus:
        condition: service_healthy
    environment:
      JWT_PRIVATE_KEY: "${JWT_PRIVATE_KEY}"
      OTEL_DOTNET_EXPERIMENTAL_OTLP_RETRY: "in_memory"
      ASPNETCORE_FORWARDEDHEADERS_ENABLED: "true"
      HTTP_PORTS: "${MARKDOWN_WEB_API_PORT}"
      ConnectionStrings__MarkDownPostgres: "Host=postgres;Port=5432;Username=postgres;Password=${POSTGRES_PASSWORD};Database=markdownpostgres;SSL Mode=Disable"
      MARKDOWNPOSTGRES_HOST: "postgres"
      MARKDOWNPOSTGRES_PORT: "5432"
      MARKDOWNPOSTGRES_USERNAME: "postgres"
      MARKDOWNPOSTGRES_PASSWORD: "${POSTGRES_PASSWORD}"
      MARKDOWNPOSTGRES_URI: "postgresql://postgres:${POSTGRES_PASSWORD}@postgres:5432/markdownpostgres"
      MARKDOWNPOSTGRES_JDBCCONNECTIONSTRING: "jdbc:postgresql://postgres:5432/markdownpostgres"
      MARKDOWNPOSTGRES_DATABASENAME: "markdownpostgres"
      ConnectionStrings__EventBus: "amqp://guest:${EVENTBUS_PASSWORD}@eventbus:5672"
      EVENTBUS_HOST: "eventbus"
      EVENTBUS_PORT: "5672"
      EVENTBUS_USERNAME: "guest"
      EVENTBUS_PASSWORD: "${EVENTBUS_PASSWORD}"
      EVENTBUS_URI: "amqp://guest:${EVENTBUS_PASSWORD}@eventbus:5672"
      OTEL_EXPORTER_OTLP_ENDPOINT: "http://docker-compose-dashboard:18889"
      OTEL_EXPORTER_OTLP_PROTOCOL: "grpc"
      OTEL_SERVICE_NAME: "markdown-web-api"
    expose:
      - "${MARKDOWN_WEB_API_PORT}"
    ports: -"${MARKDOWN_WEB_API_PORT}:9094"
    networks:
      - "aspire"
  video-web-api:
    build:
      context: ./Video.Web.API
      dockerfile: Dockerfile
    depends_on:
      # ✅ 新增依赖
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy
      eventbus:
        condition: service_healthy
    environment:
      JWT_PRIVATE_KEY: "${JWT_PRIVATE_KEY}"
      OTEL_DOTNET_EXPERIMENTAL_OTLP_RETRY: "in_memory"
      ASPNETCORE_FORWARDEDHEADERS_ENABLED: "true"
      HTTP_PORTS: "${VIDEO_WEB_API_PORT}"
      ConnectionStrings__VideoPostgres: "Host=postgres;Port=5432;Username=postgres;Password=${POSTGRES_PASSWORD};Database=videopostgres;SSL Mode=Disable"
      VIDEOPOSTGRES_HOST: "postgres"
      VIDEOPOSTGRES_PORT: "5432"
      VIDEOPOSTGRES_USERNAME: "postgres"
      VIDEOPOSTGRES_PASSWORD: "${POSTGRES_PASSWORD}"
      VIDEOPOSTGRES_URI: "postgresql://postgres:${POSTGRES_PASSWORD}@postgres:5432/videopostgres"
      VIDEOPOSTGRES_JDBCCONNECTIONSTRING: "jdbc:postgresql://postgres:5432/videopostgres"
      VIDEOPOSTGRES_DATABASENAME: "videopostgres"
      ConnectionStrings__CacheMemory: "redis:6379,password=${REDIS_PASSWORD}"
      CACHEMEMORY_HOST: "redis"
      CACHEMEMORY_PORT: "6379"
      CACHEMEMORY_PASSWORD: "${REDIS_PASSWORD}"
      CACHEMEMORY_URI: "redis://:${REDIS_PASSWORD}@redis:6379"
      ConnectionStrings__EventBus: "amqp://guest:${EVENTBUS_PASSWORD}@eventbus:5672"
      EVENTBUS_HOST: "eventbus"
      EVENTBUS_PORT: "5672"
      EVENTBUS_USERNAME: "guest"
      EVENTBUS_PASSWORD: "${EVENTBUS_PASSWORD}"
      EVENTBUS_URI: "amqp://guest:${EVENTBUS_PASSWORD}@eventbus:5672"
      FileDev_BaseUrl: "http://filedev-web-api"
      OTEL_EXPORTER_OTLP_ENDPOINT: "http://docker-compose-dashboard:18889"
      OTEL_EXPORTER_OTLP_PROTOCOL: "grpc"
      OTEL_SERVICE_NAME: "video-web-api"
    expose:
      - "${VIDEO_WEB_API_PORT}"
    ports:
      -"${VIDEO_WEB_API_PORT}:9095"
    networks:
      - "aspire"
  notblog-yarp-gateway:
    build:
      context: ./NotBlog_Yarp
      dockerfile: Dockerfile
    depends_on:
      # ✅ 新增依赖
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy
      eventbus:
        condition: service_healthy
    environment:
      JWT_PRIVATE_KEY: "${JWT_PRIVATE_KEY}"
      GATEWAY_INTERNAL_API_KEY: "${GATEWAY_INTERNAL_API_KEY}"
      ConnectionStrings__CacheMemory: "redis:6379,password=${REDIS_PASSWORD}"
      EventBus__HostName: "eventbus"
      EventBus__UserName: "guest"
      EventBus__Password: "${EVENTBUS_PASSWORD}"
      EventBus__Port: "5672"
      EventBus__ExchangeName: "notcomd_event_bus"
      EventBus__SubscriptionClientName: "yarp_permission_events"
      OTEL_DOTNET_EXPERIMENTAL_OTLP_RETRY: "in_memory"
      IDENTITY_WEB_API_HTTP: "http://identity-web-api:${IDENTITY_WEB_API_PORT}"
      services__identity-web-api__http__0: "http://identity-web-api:${IDENTITY_WEB_API_PORT}"
      IDENTITY_WEB_API_HTTPS: "https://identity-web-api:${IDENTITY_WEB_API_PORT}"
      MESSAGE_WEB_API_HTTP: "http://message-web-api:${MESSAGE_WEB_API_PORT}"
      services__message-web-api__http__0: "http://message-web-api:${MESSAGE_WEB_API_PORT}"
      MESSAGE_WEB_API_HTTPS: "https://message-web-api:${MESSAGE_WEB_API_PORT}"
      MARKDOWN_WEB_API_HTTP: "http://markdown-web-api:${MARKDOWN_WEB_API_PORT}"
      services__markdown-web-api__http__0: "http://markdown-web-api:${MARKDOWN_WEB_API_PORT}"
      MARKDOWN_WEB_API_HTTPS: "https://markdown-web-api:${MARKDOWN_WEB_API_PORT}"
      VIDEO_WEB_API_HTTP: "http://video-web-api:${VIDEO_WEB_API_PORT}"
      services__video-web-api__http__0: "http://video-web-api:${VIDEO_WEB_API_PORT}"
      VIDEO_WEB_API_HTTPS: "https://video-web-api:${VIDEO_WEB_API_PORT}"
      FILEDEV_WEB_API_HTTP: "http://filedev-web-api:${FILEDEV_WEB_API_PORT}"
      services__filedev-web-api__http__0: "http://filedev-web-api:${FILEDEV_WEB_API_PORT}"
      FILEDEV_WEB_API_HTTPS: "https://filedev-web-api:${FILEDEV_WEB_API_PORT}"
      OTEL_EXPORTER_OTLP_ENDPOINT: "http://docker-compose-dashboard:18889"
      OTEL_EXPORTER_OTLP_PROTOCOL: "grpc"
      OTEL_SERVICE_NAME: "notblog-yarp-gateway"
    networks:
      - "aspire"
    ports:
      - "${NOTBLOG_YARP_GATEWAY_PORT}:9090"
networks:
  aspire:
    driver: "bridge"
volumes:
  notblog.apphost-4e335c671b-postgres-data:
    driver: "local"
  notblog.apphost-4e335c671b-Redis-data:
    driver: "local"
  notblog.apphost-4e335c671b-EventBus-data:
    driver: "local"
