<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net10.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
        <RootNamespace>FileDev.Infrastructure</RootNamespace>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="Microsoft.EntityFrameworkCore" Version="10.0.9"/>
        <PackageReference Include="NotMediator" Version="1.0.5" />
        <PackageReference Include="StackExchange.Redis" Version="3.1.0"/>
    </ItemGroup>

    <ItemGroup>
        <ProjectReference Include="..\CacheMemory\CacheMemory.csproj"/>
        <ProjectReference Include="..\CommonsInitializer\CommonsInitializer.csproj" />
        <ProjectReference Include="..\FileDev.Domain\FileDev.Domain.csproj"/>
        <ProjectReference Include="..\JWToken\Token.JWT.csproj"/>
    </ItemGroup>

</Project>
