// <auto-generated />
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Notcomd.Identity.Server.Mapper;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Notcomd.Identity.Server.Migrations.Notcomd_User_Supplement_Db
{
    [DbContext(typeof(Notcomd_User_Supplement_DbContext))]
    partial class Notcomd_User_Supplement_DbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Notcomd.Identity.Server.Module.Notcomd_User_Image_Module", b =>
                {
                    b.Property<string>("Identity_UserName")
                        .HasColumnType("text");

                    b.Property<List<string>>("Identity_ImageUrl")
                        .HasColumnType("text[]");

                    b.HasKey("Identity_UserName");

                    b.ToTable("UserImageTable");
                });

            modelBuilder.Entity("Notcomd.Identity.Server.Module.Notcomd_User_Module", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("integer");

                    b.Property<string>("ConcurrencyStamp")
                        .HasColumnType("text");

                    b.Property<string>("Email")
                        .HasColumnType("text");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("boolean");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("boolean");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("NormalizedEmail")
                        .HasColumnType("text");

                    b.Property<string>("NormalizedUserName")
                        .HasColumnType("text");

                    b.Property<string>("Notcomd_User_Image_ModuleIdentity_UserName")
                        .HasColumnType("text");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("text");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("text");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("boolean");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("text");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("boolean");

                    b.Property<string>("UserName")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("Email");

                    b.HasIndex("Notcomd_User_Image_ModuleIdentity_UserName");

                    b.ToTable("Notcomd_User_Module");
                });

            modelBuilder.Entity("Notcomd.Identity.Server.Module.Notcomd_User_Supplement_Module", b =>
                {
                    b.Property<string>("WeChat_Numble")
                        .HasColumnType("text");

                    b.Property<bool>("UserLin_Status")
                        .HasColumnType("boolean");

                    b.Property<string>("UserRemake")
                        .HasColumnType("text");

                    b.Property<List<string>>("UserTag")
                        .IsRequired()
                        .HasColumnType("text[]");

                    b.HasKey("WeChat_Numble");

                    b.ToTable("Notcomd_User_Supplement_Modules");
                });

            modelBuilder.Entity("Notcomd.Identity.Server.Module.Notcomd_User_Module", b =>
                {
                    b.HasOne("Notcomd.Identity.Server.Module.Notcomd_User_Supplement_Module", "Notcomd_User_Supplement_Module")
                        .WithMany("Notcomd_User_Modules")
                        .HasForeignKey("Email");

                    b.HasOne("Notcomd.Identity.Server.Module.Notcomd_User_Image_Module", "Notcomd_User_Image_Module")
                        .WithMany("Notcomd_User_Modules")
                        .HasForeignKey("Notcomd_User_Image_ModuleIdentity_UserName");

                    b.Navigation("Notcomd_User_Image_Module");

                    b.Navigation("Notcomd_User_Supplement_Module");
                });

            modelBuilder.Entity("Notcomd.Identity.Server.Module.Notcomd_User_Image_Module", b =>
                {
                    b.Navigation("Notcomd_User_Modules");
                });

            modelBuilder.Entity("Notcomd.Identity.Server.Module.Notcomd_User_Supplement_Module", b =>
                {
                    b.Navigation("Notcomd_User_Modules");
                });
#pragma warning restore 612, 618
        }
    }
}
