<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net9.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
        <RootNamespace>EmailSendServer</RootNamespace>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="MailKit" Version="4.13.0" />
        <PackageReference Include="Microsoft.Extensions.Configuration.Abstractions" Version="9.0.9" />
        <PackageReference Include="Microsoft.Extensions.Options" Version="9.0.9" />
    </ItemGroup>

    <ItemGroup>
        <ProjectReference Include="..\DomainCommon\DomainCommon.csproj" />
        <ProjectReference Include="..\Evenbus\Evenbus.csproj" />
    </ItemGroup>

</Project>
