// <auto-generated />
using System;
using System.Collections.Generic;
using FileDev.Infrastructure.EntityFramework;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace FileDev.Infrastructure.Migrations
{
    [DbContext(typeof(NotFileDbContext))]
    [Migration("20260913174043_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("FileDev.Domain.Entities.ContentAttachmentRef", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("ActiveRefs")
                        .HasColumnType("integer");

                    b.Property<string>("ContentId")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<int>("ContentType")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("FileUri")
                        .IsRequired()
                        .HasMaxLength(1024)
                        .HasColumnType("character varying(1024)");

                    b.Property<Guid>("SourceFileId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("FileUri")
                        .HasDatabaseName("IX_ContentAttachmentRef_FileUri");

                    b.HasIndex("ContentId", "ContentType")
                        .HasDatabaseName("IX_ContentAttachmentRef_Content");

                    b.ToTable("ContentAttachmentRef", (string)null);
                });

            modelBuilder.Entity("FileDev.Domain.Entities.NotFile", b =>
                {
                    b.Property<Guid>("FileId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("ContentHash")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<DateTimeOffset?>("DeleteTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("FileDescription")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<int>("FileIdentity")
                        .HasColumnType("integer");

                    b.Property<string>("FileMd5")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<long>("FileSize")
                        .HasColumnType("bigint");

                    b.PrimitiveCollection<List<string>>("FileTags")
                        .IsRequired()
                        .HasColumnType("text[]");

                    b.Property<string>("FileUri")
                        .IsRequired()
                        .HasMaxLength(1024)
                        .HasColumnType("character varying(1024)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<int>("ShardCount")
                        .HasColumnType("integer");

                    b.Property<int>("Source")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset?>("StorageExpiresAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset>("StorageUpdatedUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Tier")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset>("UpdateTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset>("UploadTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.Property<string>("VolumeId")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.HasKey("FileId");

                    b.HasIndex("FileId")
                        .IsUnique()
                        .HasDatabaseName("IX_NotFile_FileId");

                    b.HasIndex("FileUri")
                        .HasDatabaseName("IX_NotFile_FileUri");

                    b.HasIndex("UserId")
                        .HasDatabaseName("IX_NotFile_UserId");

                    b.HasIndex("VolumeId")
                        .HasDatabaseName("IX_NotFile_VolumeId");

                    b.HasIndex("FileMd5", "FileSize")
                        .HasDatabaseName("IX_NotFile_FileMd5_FileSize");

                    b.HasIndex("UserId", "IsDeleted")
                        .HasDatabaseName("IX_NotFile_UserId_IsDeleted");

                    b.HasIndex("UserId", "Source")
                        .HasDatabaseName("IX_NotFile_UserId_Source");

                    b.ToTable("NotFile", (string)null);
                });

            modelBuilder.Entity("FileDev.Domain.Entities.NotFileTag", b =>
                {
                    b.Property<Guid>("TagId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("DefaultKind")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0);

                    b.Property<DateTimeOffset?>("DeleteTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("FileIds")
                        .IsRequired()
                        .HasMaxLength(-1)
                        .HasColumnType("text");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<string>("TagDescription")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("TagName")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<DateTimeOffset>("UpdateTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset>("UploadTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("TagId");

                    b.HasIndex("UserId")
                        .HasDatabaseName("IX_NotFileTag_UserId");

                    b.HasIndex("UserId", "DefaultKind")
                        .HasDatabaseName("IX_NotFileTag_UserId_DefaultKind");

                    b.HasIndex("UserId", "TagName")
                        .IsUnique()
                        .HasDatabaseName("IX_NotFileTag_UserId_TagName");

                    b.ToTable("NotFileTag", (string)null);
                });

            modelBuilder.Entity("FileDev.Domain.Entities.NotFileVolume", b =>
                {
                    b.Property<string>("VolumeId")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Kind")
                        .HasColumnType("integer");

                    b.Property<long>("ObjectCount")
                        .HasColumnType("bigint");

                    b.Property<long>("PartCount")
                        .HasColumnType("bigint");

                    b.Property<string>("RootPath")
                        .IsRequired()
                        .HasMaxLength(1024)
                        .HasColumnType("character varying(1024)");

                    b.Property<string>("TenantId")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<long>("TotalBytes")
                        .HasColumnType("bigint");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("VolumeId");

                    b.HasIndex("TenantId")
                        .HasDatabaseName("IX_NotFileVolume_TenantId");

                    b.HasIndex("VolumeId")
                        .IsUnique()
                        .HasDatabaseName("IX_NotFileVolume_VolumeId");

                    b.ToTable("NotFileVolume", (string)null);
                });

            modelBuilder.Entity("FileDev.Domain.Entities.UserFileInfo", b =>
                {
                    b.Property<Guid>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<long>("TotalQuotaBytes")
                        .HasColumnType("bigint");

                    b.Property<DateTimeOffset>("UpdateTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<long>("UsedBytes")
                        .HasColumnType("bigint");

                    b.HasKey("UserId");

                    b.ToTable("UserFileInfo", (string)null);
                });

            modelBuilder.Entity("FileDev.Infrastructure.Idempotent.ClientRequest", b =>
                {
                    b.Property<Guid>("ClientRequestId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("ClientRequestName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("CreatedDate")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("ClientRequestId");

                    b.ToTable("ClientRequest", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
