// <auto-generated />
using System;
using System.Collections.Generic;
using FileDev.Infrastructure.EntityFramework;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace FileDev.Infrastructure.Migrations
{
    [DbContext(typeof(NotFileDbContext))]
    partial class NotFileDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.HasSequence("NotFileGroupseq")
                .IncrementsBy(10);

            modelBuilder.HasSequence("NotFileSeq")
                .IncrementsBy(10);

            modelBuilder.Entity("FileDev.Domain.Entities.FileChunkRecord", b =>
                {
                    b.Property<Guid>("RecordId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("ChunkSize")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("CompletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("FileDescription")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("FileIdentity")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<string>("FileKey")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)");

                    b.Property<string>("FileMd5")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("FileTags")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<string>("FileType")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<int>("Id")
                        .HasColumnType("integer");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<int>("TotalChunks")
                        .HasColumnType("integer");

                    b.Property<long>("TotalSize")
                        .HasColumnType("bigint");

                    b.Property<string>("UploadedChunks")
                        .IsRequired()
                        .HasMaxLength(4000)
                        .HasColumnType("character varying(4000)")
                        .HasColumnName("UploadedChunksCsv");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("RecordId");

                    b.HasIndex("FileKey")
                        .IsUnique()
                        .HasDatabaseName("IX_FileChunkRecord_FileKey");

                    b.HasIndex("UserId")
                        .HasDatabaseName("IX_FileChunkRecord_UserId");

                    b.HasIndex("Status", "CreatedAt")
                        .HasDatabaseName("IX_FileChunkRecord_Status_CreatedAt");

                    b.ToTable("FileChunkRecord", (string)null);
                });

            modelBuilder.Entity("FileDev.Domain.Entities.NotFile", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseHiLo(b.Property<int>("Id"), "NotFileSeq");

                    b.Property<DateTime?>("DeleteTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("FileDescription")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("FileId")
                        .HasColumnType("uuid");

                    b.Property<int>("FileIdentity")
                        .HasColumnType("integer");

                    b.Property<string>("FileMd5")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<long>("FileSize")
                        .HasColumnType("bigint");

                    b.PrimitiveCollection<HashSet<string>>("FileTags")
                        .IsRequired()
                        .HasColumnType("text[]");

                    b.Property<int>("FileType")
                        .HasColumnType("integer");

                    b.Property<string>("FileUri")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("UpdateTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("UploadTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.ToTable("NotFile", (string)null);
                });

            modelBuilder.Entity("FileDev.Domain.Entities.NotFileGroup", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseHiLo(b.Property<int>("Id"), "NotFileGroupseq");

                    b.Property<string>("FileGroupDescription")
                        .HasColumnType("text");

                    b.Property<string>("FileGroupName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.PrimitiveCollection<HashSet<string>>("FileGroupTags")
                        .IsRequired()
                        .HasColumnType("text[]");

                    b.Property<int>("FileIdentity")
                        .HasColumnType("integer");

                    b.Property<int>("FileType")
                        .HasColumnType("integer");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<Guid>("NotFileGroupId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("UpdateTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("UploadTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.ToTable("NotFileGroup", (string)null);
                });

            modelBuilder.Entity("FileDev.Infrastructure.Idempotent.ClientRequest", b =>
                {
                    b.Property<Guid>("ClientRequestId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("ClientRequestName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("CreatedDate")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("ClientRequestId");

                    b.ToTable("ClientRequest", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
