<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net8.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
        <RootNamespace>ConsoleApp1</RootNamespace>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="Microsoft.EntityFrameworkCore" Version="8.0.5"/>
    </ItemGroup>

    <ItemGroup>
        <ProjectReference Include="..\FileDev.Domain\FileDev.Domain.csproj"/>
    </ItemGroup>

</Project>
