// <auto-generated />
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Video.Infrastructure.EntityFramework;

#nullable disable

namespace Video.Infrastructure.Migrations
{
    [DbContext(typeof(VideoDbContext))]
    [Migration("20250404061522_Initial")]
    partial class Initial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.14")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Video.Domain.Entities.VideoBarrage", b =>
                {
                    b.Property<Guid>("VideoBarrageGuid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("UserGuid")
                        .HasColumnType("uuid");

                    b.Property<string>("VideoBarrageBody")
                        .HasColumnType("text");

                    b.Property<Guid>("VideoGuid")
                        .HasColumnType("uuid");

                    b.HasKey("VideoBarrageGuid");

                    b.ToTable("VideoBarrage");
                });

            modelBuilder.Entity("Video.Domain.Entities.VideoCollection", b =>
                {
                    b.Property<Guid>("VideoCollectionGuid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<List<Guid>>("AffiliatedUser")
                        .IsRequired()
                        .HasColumnType("uuid[]");

                    b.Property<string>("VideoCollectionBriefIntroduction")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("VideoCollectionName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<List<Guid>>("VideoGuid")
                        .IsRequired()
                        .HasColumnType("uuid[]");

                    b.HasKey("VideoCollectionGuid");

                    b.HasIndex("VideoCollectionGuid");

                    b.ToTable("VideoCollection", (string)null);
                });

            modelBuilder.Entity("Video.Domain.Entities.VideoReview", b =>
                {
                    b.Property<Guid>("VideoReviewGuid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid?>("RootReview")
                        .HasColumnType("uuid");

                    b.Property<Guid>("UserGuid")
                        .HasColumnType("uuid");

                    b.Property<Guid>("VideoGuid")
                        .HasColumnType("uuid");

                    b.Property<string>("VideoReviewBody")
                        .HasColumnType("text");

                    b.HasKey("VideoReviewGuid");

                    b.HasIndex("VideoGuid");

                    b.HasIndex("VideoReviewGuid");

                    b.ToTable("VideoReview", (string)null);
                });

            modelBuilder.Entity("Video.Domain.Entities.Videos", b =>
                {
                    b.Property<Guid>("VideoGuid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<List<Guid>>("AffiliatedUserGuid")
                        .IsRequired()
                        .HasColumnType("uuid[]");

                    b.Property<string>("BriefIntroduction")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<List<Guid>>("ChildVideosList")
                        .HasColumnType("uuid[]");

                    b.Property<string>("VideoCover")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("VideoFileUri")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("VideoName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<List<string>>("VideoTags")
                        .IsRequired()
                        .HasColumnType("text[]")
                        .HasColumnName("VideoTags");

                    b.HasKey("VideoGuid");

                    b.HasIndex("VideoGuid");

                    b.ToTable("Videos");
                });

            modelBuilder.Entity("Video.Domain.Entities.VideoCollection", b =>
                {
                    b.OwnsOne("Video.Domain.Entities.TimeSpace", "TimeSpace", b1 =>
                        {
                            b1.Property<Guid>("VideoCollectionGuid")
                                .HasColumnType("uuid");

                            b1.Property<DateTimeOffset>("CreateAt")
                                .HasColumnType("timestamp with time zone")
                                .HasColumnName("CreateTime");

                            b1.Property<DateTimeOffset>("UpdateAt")
                                .HasColumnType("timestamp with time zone")
                                .HasColumnName("UpdateTime");

                            b1.Property<DateTimeOffset>("createAt")
                                .HasColumnType("timestamp with time zone");

                            b1.Property<DateTimeOffset>("updateAt")
                                .HasColumnType("timestamp with time zone");

                            b1.HasKey("VideoCollectionGuid");

                            b1.ToTable("VideoCollection");

                            b1.ToJson("TimeSpace");

                            b1.WithOwner()
                                .HasForeignKey("VideoCollectionGuid");
                        });

                    b.OwnsOne("Video.Domain.Entities.VideoControl", "VideoControl", b1 =>
                        {
                            b1.Property<Guid>("VideoCollectionGuid")
                                .HasColumnType("uuid");

                            b1.Property<int>("AuthorVideo")
                                .HasColumnType("integer")
                                .HasColumnName("AuthorVideo");

                            b1.Property<bool>("VideoDelete")
                                .HasColumnType("boolean")
                                .HasColumnName("VideoDelete");

                            b1.Property<bool>("VideoDisplay")
                                .HasColumnType("boolean")
                                .HasColumnName("VideoDisplay");

                            b1.HasKey("VideoCollectionGuid");

                            b1.ToTable("VideoCollection");

                            b1.ToJson("VideoControl");

                            b1.WithOwner()
                                .HasForeignKey("VideoCollectionGuid");

                            b1.OwnsOne("Video.Domain.Entities.VideoProtectedTime", "VideoProtectedTime", b2 =>
                                {
                                    b2.Property<Guid>("VideoControlVideoCollectionGuid")
                                        .HasColumnType("uuid");

                                    b2.Property<DateTime>("EndTime")
                                        .HasColumnType("timestamp with time zone")
                                        .HasColumnName("EndTime");

                                    b2.Property<DateTime>("StartTime")
                                        .HasColumnType("timestamp with time zone")
                                        .HasColumnName("StartTime");

                                    b2.HasKey("VideoControlVideoCollectionGuid");

                                    b2.ToTable("VideoCollection");

                                    b2.WithOwner()
                                        .HasForeignKey("VideoControlVideoCollectionGuid");
                                });

                            b1.Navigation("VideoProtectedTime");
                        });

                    b.OwnsOne("Video.Domain.Entities.VideoQuote", "VideoQuote", b1 =>
                        {
                            b1.Property<Guid>("VideoCollectionGuid")
                                .HasColumnType("uuid");

                            b1.Property<long>("Ballot")
                                .HasColumnType("bigint")
                                .HasColumnName("c_Ballot");

                            b1.Property<long>("Down")
                                .HasColumnType("bigint")
                                .HasColumnName("c_Down");

                            b1.Property<long>("Share")
                                .HasColumnType("bigint")
                                .HasColumnName("c_Share");

                            b1.Property<long>("Stars")
                                .HasColumnType("bigint")
                                .HasColumnName("c_Stars");

                            b1.Property<long>("Upvote")
                                .HasColumnType("bigint")
                                .HasColumnName("c_Upvote");

                            b1.Property<long>("Watch")
                                .HasColumnType("bigint")
                                .HasColumnName("c_Watch");

                            b1.HasKey("VideoCollectionGuid");

                            b1.ToTable("VideoCollection");

                            b1.ToJson("VideoQuote");

                            b1.WithOwner()
                                .HasForeignKey("VideoCollectionGuid");
                        });

                    b.Navigation("TimeSpace")
                        .IsRequired();

                    b.Navigation("VideoControl")
                        .IsRequired();

                    b.Navigation("VideoQuote")
                        .IsRequired();
                });

            modelBuilder.Entity("Video.Domain.Entities.VideoReview", b =>
                {
                    b.HasOne("Video.Domain.Entities.Videos", null)
                        .WithMany("VideoReviews")
                        .HasForeignKey("VideoGuid")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.OwnsOne("Video.Domain.Entities.TimeSpace", "TimeSpace", b1 =>
                        {
                            b1.Property<Guid>("VideoReviewGuid")
                                .HasColumnType("uuid");

                            b1.Property<DateTimeOffset>("CreateAt")
                                .HasColumnType("timestamp with time zone")
                                .HasColumnName("CreateTime");

                            b1.Property<DateTimeOffset>("UpdateAt")
                                .HasColumnType("timestamp with time zone")
                                .HasColumnName("UpdateTime");

                            b1.Property<DateTimeOffset>("createAt")
                                .HasColumnType("timestamp with time zone");

                            b1.Property<DateTimeOffset>("updateAt")
                                .HasColumnType("timestamp with time zone");

                            b1.HasKey("VideoReviewGuid");

                            b1.ToTable("VideoReview");

                            b1.ToJson("TimeSpace");

                            b1.WithOwner()
                                .HasForeignKey("VideoReviewGuid");
                        });

                    b.OwnsOne("Video.Domain.Entities.VideoControl", "VideoControl", b1 =>
                        {
                            b1.Property<Guid>("VideoReviewGuid")
                                .HasColumnType("uuid");

                            b1.Property<int>("AuthorVideo")
                                .HasColumnType("integer")
                                .HasColumnName("AuthorVideo");

                            b1.Property<bool>("VideoDelete")
                                .HasColumnType("boolean")
                                .HasColumnName("VideoDelete");

                            b1.Property<bool>("VideoDisplay")
                                .HasColumnType("boolean")
                                .HasColumnName("VideoDisplay");

                            b1.HasKey("VideoReviewGuid");

                            b1.ToTable("VideoReview");

                            b1.ToJson("VideoControl");

                            b1.WithOwner()
                                .HasForeignKey("VideoReviewGuid");

                            b1.OwnsOne("Video.Domain.Entities.VideoProtectedTime", "VideoProtectedTime", b2 =>
                                {
                                    b2.Property<Guid>("VideoControlVideoReviewGuid")
                                        .HasColumnType("uuid");

                                    b2.Property<DateTime>("EndTime")
                                        .HasColumnType("timestamp with time zone")
                                        .HasColumnName("EndTime");

                                    b2.Property<DateTime>("StartTime")
                                        .HasColumnType("timestamp with time zone")
                                        .HasColumnName("StartTime");

                                    b2.HasKey("VideoControlVideoReviewGuid");

                                    b2.ToTable("VideoReview");

                                    b2.ToJson("VideoProtectedTime");

                                    b2.WithOwner()
                                        .HasForeignKey("VideoControlVideoReviewGuid");
                                });

                            b1.Navigation("VideoProtectedTime");
                        });

                    b.OwnsOne("Video.Domain.Entities.VideoQuote", "VideoQuote", b1 =>
                        {
                            b1.Property<Guid>("VideoReviewGuid")
                                .HasColumnType("uuid");

                            b1.Property<long>("Ballot")
                                .HasColumnType("bigint")
                                .HasColumnName("c_Ballot");

                            b1.Property<long>("Down")
                                .HasColumnType("bigint")
                                .HasColumnName("c_Down");

                            b1.Property<long>("Share")
                                .HasColumnType("bigint")
                                .HasColumnName("c_Share");

                            b1.Property<long>("Stars")
                                .HasColumnType("bigint")
                                .HasColumnName("c_Stars");

                            b1.Property<long>("Upvote")
                                .HasColumnType("bigint")
                                .HasColumnName("c_Upvote");

                            b1.Property<long>("Watch")
                                .HasColumnType("bigint")
                                .HasColumnName("c_Watch");

                            b1.HasKey("VideoReviewGuid");

                            b1.ToTable("VideoReview");

                            b1.ToJson("VideoQuote");

                            b1.WithOwner()
                                .HasForeignKey("VideoReviewGuid");
                        });

                    b.Navigation("TimeSpace")
                        .IsRequired();

                    b.Navigation("VideoControl")
                        .IsRequired();

                    b.Navigation("VideoQuote")
                        .IsRequired();
                });

            modelBuilder.Entity("Video.Domain.Entities.Videos", b =>
                {
                    b.OwnsOne("Video.Domain.Entities.TimeSpace", "TimeSpace", b1 =>
                        {
                            b1.Property<Guid>("VideosVideoGuid")
                                .HasColumnType("uuid");

                            b1.Property<DateTimeOffset>("CreateAt")
                                .HasColumnType("timestamp with time zone")
                                .HasColumnName("CreateTime");

                            b1.Property<DateTimeOffset>("UpdateAt")
                                .HasColumnType("timestamp with time zone")
                                .HasColumnName("UpdateTime");

                            b1.Property<DateTimeOffset>("createAt")
                                .HasColumnType("timestamp with time zone");

                            b1.Property<DateTimeOffset>("updateAt")
                                .HasColumnType("timestamp with time zone");

                            b1.HasKey("VideosVideoGuid");

                            b1.ToTable("Videos");

                            b1.ToJson("TimeSpace");

                            b1.WithOwner()
                                .HasForeignKey("VideosVideoGuid");
                        });

                    b.OwnsOne("Video.Domain.Entities.VideoControl", "VideoControl", b1 =>
                        {
                            b1.Property<Guid>("VideosVideoGuid")
                                .HasColumnType("uuid");

                            b1.Property<int>("AuthorVideo")
                                .HasColumnType("integer")
                                .HasColumnName("AuthorVideo");

                            b1.Property<bool>("VideoDelete")
                                .HasColumnType("boolean")
                                .HasColumnName("VideoDelete");

                            b1.Property<bool>("VideoDisplay")
                                .HasColumnType("boolean")
                                .HasColumnName("VideoDisplay");

                            b1.HasKey("VideosVideoGuid");

                            b1.ToTable("Videos");

                            b1.ToJson("VideoControl");

                            b1.WithOwner()
                                .HasForeignKey("VideosVideoGuid");

                            b1.OwnsOne("Video.Domain.Entities.VideoProtectedTime", "VideoProtectedTime", b2 =>
                                {
                                    b2.Property<Guid>("VideoControlVideosVideoGuid")
                                        .HasColumnType("uuid");

                                    b2.Property<DateTime>("EndTime")
                                        .HasColumnType("timestamp with time zone")
                                        .HasColumnName("EndTime");

                                    b2.Property<DateTime>("StartTime")
                                        .HasColumnType("timestamp with time zone")
                                        .HasColumnName("StartTime");

                                    b2.HasKey("VideoControlVideosVideoGuid");

                                    b2.ToTable("Videos");

                                    b2.ToJson("VideoProtectedTime");

                                    b2.WithOwner()
                                        .HasForeignKey("VideoControlVideosVideoGuid");
                                });

                            b1.Navigation("VideoProtectedTime");
                        });

                    b.OwnsOne("Video.Domain.Entities.VideoQuote", "VideoQuote", b1 =>
                        {
                            b1.Property<Guid>("VideosVideoGuid")
                                .HasColumnType("uuid");

                            b1.Property<long>("Ballot")
                                .HasColumnType("bigint")
                                .HasColumnName("v_Ballot");

                            b1.Property<long>("Down")
                                .HasColumnType("bigint")
                                .HasColumnName("v_Down");

                            b1.Property<long>("Share")
                                .HasColumnType("bigint")
                                .HasColumnName("v_Share");

                            b1.Property<long>("Stars")
                                .HasColumnType("bigint")
                                .HasColumnName("v_Stars");

                            b1.Property<long>("Upvote")
                                .HasColumnType("bigint")
                                .HasColumnName("v_Upvote");

                            b1.Property<long>("Watch")
                                .HasColumnType("bigint")
                                .HasColumnName("v_Watch");

                            b1.HasKey("VideosVideoGuid");

                            b1.ToTable("Videos");

                            b1.ToJson("VideoQuote");

                            b1.WithOwner()
                                .HasForeignKey("VideosVideoGuid");
                        });

                    b.Navigation("TimeSpace")
                        .IsRequired();

                    b.Navigation("VideoControl")
                        .IsRequired();

                    b.Navigation("VideoQuote")
                        .IsRequired();
                });

            modelBuilder.Entity("Video.Domain.Entities.Videos", b =>
                {
                    b.Navigation("VideoReviews");
                });
#pragma warning restore 612, 618
        }
    }
}
