// <auto-generated />
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Video.Infrastructure.EntityFramework;

#nullable disable

namespace Video.Infrastructure.Migrations
{
    [DbContext(typeof(VideoDbContext))]
    partial class VideoDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Video.Domain.Entities.VideoBarrage", b =>
                {
                    b.Property<Guid>("VideoBarrageGuid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("BarrageType")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasDefaultValue("Text");

                    b.Property<bool>("IsDelete")
                        .HasColumnType("boolean");

                    b.Property<long?>("TimeAt")
                        .HasColumnType("bigint");

                    b.Property<Guid>("UserGuid")
                        .HasColumnType("uuid");

                    b.Property<string>("VideoBarrageBody")
                        .HasColumnType("text");

                    b.Property<Guid>("VideoGuid")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("VideosVideoGuid")
                        .HasColumnType("uuid");

                    b.HasKey("VideoBarrageGuid");

                    b.HasIndex("UserGuid");

                    b.HasIndex("VideoGuid");

                    b.HasIndex("VideosVideoGuid");

                    b.ToTable("VideoBarrage", (string)null);
                });

            modelBuilder.Entity("Video.Domain.Entities.VideoCollection", b =>
                {
                    b.Property<Guid>("VideoCollectionGuid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<string>("VideoCollectionBriefIntroduction")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("VideoCollectionName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("VideoNvid")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("VideoCollectionGuid");

                    b.HasIndex("VideoCollectionGuid");

                    b.ToTable("VideoCollection", (string)null);
                });

            modelBuilder.Entity("Video.Domain.Entities.VideoHistory", b =>
                {
                    b.Property<Guid>("VideoHistoryGuid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<TimeSpan>("Duration")
                        .HasColumnType("interval");

                    b.Property<DateTimeOffset?>("EndTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsCompleted")
                        .HasColumnType("boolean");

                    b.Property<double>("LastPositionSeconds")
                        .HasColumnType("double precision");

                    b.Property<double>("Progress")
                        .HasColumnType("double precision");

                    b.Property<DateTimeOffset>("StartTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("UserGuid")
                        .HasColumnType("uuid");

                    b.Property<Guid>("VideoGuid")
                        .HasColumnType("uuid");

                    b.HasKey("VideoHistoryGuid");

                    b.HasIndex("VideoHistoryGuid");

                    b.ToTable("VideoHistory", (string)null);
                });

            modelBuilder.Entity("Video.Domain.Entities.VideoReview", b =>
                {
                    b.Property<Guid>("VideoReviewGuid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid?>("RootReview")
                        .HasColumnType("uuid");

                    b.Property<Guid>("UserGuid")
                        .HasColumnType("uuid");

                    b.Property<Guid>("VideoGuid")
                        .HasColumnType("uuid");

                    b.HasKey("VideoReviewGuid");

                    b.HasIndex("RootReview");

                    b.HasIndex("UserGuid");

                    b.HasIndex("VideoGuid");

                    b.HasIndex("VideoReviewGuid");

                    b.ToTable("VideoReview", (string)null);
                });

            modelBuilder.Entity("Video.Domain.Entities.Videos", b =>
                {
                    b.Property<Guid>("VideoGuid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.PrimitiveCollection<List<Guid>>("Affiliated")
                        .IsRequired()
                        .HasColumnType("uuid[]");

                    b.Property<string>("BriefIntroduction")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<string>("VideoCover")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("VideoFileUri")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("VideoName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("VideoNvid")
                        .IsRequired()
                        .HasColumnType("text");

                    b.PrimitiveCollection<List<string>>("VideoTags")
                        .IsRequired()
                        .HasColumnType("text[]")
                        .HasColumnName("VideoTags");

                    b.HasKey("VideoGuid");

                    b.HasIndex("VideoName");

                    b.HasIndex("VideoNvid");

                    b.HasIndex("VideoTags");

                    b.ToTable("Video", (string)null);
                });

            modelBuilder.Entity("Video.Domain.Entities.VideoBarrage", b =>
                {
                    b.HasOne("Video.Domain.Entities.Videos", null)
                        .WithMany("VideoBarrageList")
                        .HasForeignKey("VideosVideoGuid");

                    b.OwnsOne("Video.Domain.ValueObjects.TimeSpace", "TimeSpace", b1 =>
                        {
                            b1.Property<Guid>("VideoBarrageGuid");

                            b1.Property<DateTimeOffset>("CreateAt")
                                .HasJsonPropertyName("CreateTime");

                            b1.Property<DateTimeOffset>("UpdateAt")
                                .HasJsonPropertyName("UpdateTime");

                            b1.HasKey("VideoBarrageGuid");

                            b1.ToTable("VideoBarrage");

                            b1
                                .ToJson("TimeSpace")
                                .HasColumnType("jsonb");

                            b1.WithOwner()
                                .HasForeignKey("VideoBarrageGuid");
                        });

                    b.OwnsOne("Video.Domain.ValueObjects.VideoControl", "VideoControl", b1 =>
                        {
                            b1.Property<Guid>("VideoBarrageGuid");

                            b1.Property<int>("AuthorVideo")
                                .HasJsonPropertyName("AuthorVideo");

                            b1.Property<int>("BarrageControl");

                            b1.Property<bool>("VideoDelete")
                                .HasJsonPropertyName("VideoDelete");

                            b1.Property<bool>("VideoDisplay")
                                .HasJsonPropertyName("VideoDisplay");

                            b1.HasKey("VideoBarrageGuid");

                            b1.ToTable("VideoBarrage");

                            b1
                                .ToJson("VideoControl")
                                .HasColumnType("jsonb");

                            b1.WithOwner()
                                .HasForeignKey("VideoBarrageGuid");

                            b1.OwnsOne("Video.Domain.ValueObjects.TimeSpace", "TimeSpace", b2 =>
                                {
                                    b2.Property<Guid>("VideoControlVideoBarrageGuid");

                                    b2.Property<DateTimeOffset>("CreateAt")
                                        .HasJsonPropertyName("VideoControlCreateTime");

                                    b2.Property<DateTimeOffset>("UpdateAt")
                                        .HasJsonPropertyName("VideoControlUpdateTime");

                                    b2.HasKey("VideoControlVideoBarrageGuid");

                                    b2.ToTable("VideoBarrage");

                                    b2.WithOwner()
                                        .HasForeignKey("VideoControlVideoBarrageGuid");
                                });

                            b1.OwnsOne("Video.Domain.Entities.VideoProtectedTime", "VideoProtectedTime", b2 =>
                                {
                                    b2.Property<Guid>("VideoControlVideoBarrageGuid");

                                    b2.Property<DateTimeOffset>("EndTime")
                                        .HasJsonPropertyName("VideoProtectedEndTime");

                                    b2.Property<DateTimeOffset>("StartTime")
                                        .HasJsonPropertyName("VideoProtectedStartTime");

                                    b2.HasKey("VideoControlVideoBarrageGuid");

                                    b2.ToTable("VideoBarrage");

                                    b2.WithOwner()
                                        .HasForeignKey("VideoControlVideoBarrageGuid");
                                });

                            b1.Navigation("TimeSpace")
                                .IsRequired();

                            b1.Navigation("VideoProtectedTime");
                        });

                    b.OwnsMany("Video.Domain.ValueObjects.VideoImage", "VideoImages", b1 =>
                        {
                            b1.Property<Guid>("VideoBarrageGuid");

                            b1.Property<int>("__synthesizedOrdinal")
                                .ValueGeneratedOnAdd();

                            b1.Property<string>("Description");

                            b1.Property<long?>("FileSize");

                            b1.Property<string>("Format")
                                .HasMaxLength(16);

                            b1.Property<int?>("Height");

                            b1.Property<string>("ImageUrl")
                                .IsRequired();

                            b1.Property<int>("SortOrder");

                            b1.Property<string>("ThumbnailUrl");

                            b1.Property<int?>("Width");

                            b1.HasKey("VideoBarrageGuid", "__synthesizedOrdinal");

                            b1.ToTable("VideoBarrage");

                            b1
                                .ToJson("VideoImages")
                                .HasColumnType("jsonb");

                            b1.WithOwner()
                                .HasForeignKey("VideoBarrageGuid");
                        });

                    b.OwnsOne("Video.Domain.ValueObjects.VideoQuote", "VideoQuote", b1 =>
                        {
                            b1.Property<Guid>("VideoBarrageGuid");

                            b1.Property<long>("Ballot")
                                .HasJsonPropertyName("b_Ballot");

                            b1.Property<long>("Down")
                                .HasJsonPropertyName("b_Down");

                            b1.Property<long>("Share")
                                .HasJsonPropertyName("b_Share");

                            b1.Property<long>("Stars")
                                .HasJsonPropertyName("b_Stars");

                            b1.Property<long>("Upvote")
                                .HasJsonPropertyName("b_Upvote");

                            b1.Property<long>("Watch")
                                .HasJsonPropertyName("b_Watch");

                            b1.HasKey("VideoBarrageGuid");

                            b1.ToTable("VideoBarrage");

                            b1
                                .ToJson("VideoQuote")
                                .HasColumnType("jsonb");

                            b1.WithOwner()
                                .HasForeignKey("VideoBarrageGuid");
                        });

                    b.Navigation("TimeSpace")
                        .IsRequired();

                    b.Navigation("VideoControl")
                        .IsRequired();

                    b.Navigation("VideoImages");

                    b.Navigation("VideoQuote")
                        .IsRequired();
                });

            modelBuilder.Entity("Video.Domain.Entities.VideoCollection", b =>
                {
                    b.OwnsOne("Video.Domain.ValueObjects.TimeSpace", "TimeSpace", b1 =>
                        {
                            b1.Property<Guid>("VideoCollectionGuid");

                            b1.Property<DateTimeOffset>("CreateAt")
                                .HasJsonPropertyName("CreateTime");

                            b1.Property<DateTimeOffset>("UpdateAt")
                                .HasJsonPropertyName("UpdateTime");

                            b1.HasKey("VideoCollectionGuid");

                            b1.ToTable("VideoCollection");

                            b1
                                .ToJson("TimeSpace")
                                .HasColumnType("jsonb");

                            b1.WithOwner()
                                .HasForeignKey("VideoCollectionGuid");
                        });

                    b.OwnsOne("Video.Domain.ValueObjects.VideoControl", "VideoControl", b1 =>
                        {
                            b1.Property<Guid>("VideoCollectionGuid");

                            b1.Property<int>("AuthorVideo")
                                .HasJsonPropertyName("AuthorVideo");

                            b1.Property<int>("BarrageControl");

                            b1.Property<bool>("VideoDelete")
                                .HasJsonPropertyName("VideoDelete");

                            b1.Property<bool>("VideoDisplay")
                                .HasJsonPropertyName("VideoDisplay");

                            b1.HasKey("VideoCollectionGuid");

                            b1.ToTable("VideoCollection");

                            b1
                                .ToJson("VideoControl")
                                .HasColumnType("jsonb");

                            b1.WithOwner()
                                .HasForeignKey("VideoCollectionGuid");

                            b1.OwnsOne("Video.Domain.ValueObjects.TimeSpace", "TimeSpace", b2 =>
                                {
                                    b2.Property<Guid>("VideoControlVideoCollectionGuid");

                                    b2.Property<DateTimeOffset>("CreateAt")
                                        .HasJsonPropertyName("VideoControlCreateTime");

                                    b2.Property<DateTimeOffset>("UpdateAt")
                                        .HasJsonPropertyName("VideoControlUpdateTime");

                                    b2.HasKey("VideoControlVideoCollectionGuid");

                                    b2.ToTable("VideoCollection");

                                    b2.WithOwner()
                                        .HasForeignKey("VideoControlVideoCollectionGuid");
                                });

                            b1.OwnsOne("Video.Domain.Entities.VideoProtectedTime", "VideoProtectedTime", b2 =>
                                {
                                    b2.Property<Guid>("VideoControlVideoCollectionGuid");

                                    b2.Property<DateTimeOffset>("EndTime")
                                        .HasJsonPropertyName("VideoProtectedEndTime");

                                    b2.Property<DateTimeOffset>("StartTime")
                                        .HasJsonPropertyName("VideoProtectedStartTime");

                                    b2.HasKey("VideoControlVideoCollectionGuid");

                                    b2.ToTable("VideoCollection");

                                    b2.WithOwner()
                                        .HasForeignKey("VideoControlVideoCollectionGuid");
                                });

                            b1.Navigation("TimeSpace")
                                .IsRequired();

                            b1.Navigation("VideoProtectedTime");
                        });

                    b.OwnsOne("Video.Domain.ValueObjects.VideoQuote", "VideoQuote", b1 =>
                        {
                            b1.Property<Guid>("VideoCollectionGuid");

                            b1.Property<long>("Ballot")
                                .HasJsonPropertyName("c_Ballot");

                            b1.Property<long>("Down")
                                .HasJsonPropertyName("c_Down");

                            b1.Property<long>("Share")
                                .HasJsonPropertyName("c_Share");

                            b1.Property<long>("Stars")
                                .HasJsonPropertyName("c_Stars");

                            b1.Property<long>("Upvote")
                                .HasJsonPropertyName("c_Upvote");

                            b1.Property<long>("Watch")
                                .HasJsonPropertyName("c_Watch");

                            b1.HasKey("VideoCollectionGuid");

                            b1.ToTable("VideoCollection");

                            b1
                                .ToJson("VideoQuote")
                                .HasColumnType("jsonb");

                            b1.WithOwner()
                                .HasForeignKey("VideoCollectionGuid");
                        });

                    b.Navigation("TimeSpace")
                        .IsRequired();

                    b.Navigation("VideoControl")
                        .IsRequired();

                    b.Navigation("VideoQuote")
                        .IsRequired();
                });

            modelBuilder.Entity("Video.Domain.Entities.VideoHistory", b =>
                {
                    b.OwnsOne("Video.Domain.ValueObjects.TimeSpace", "TimeSpace", b1 =>
                        {
                            b1.Property<Guid>("VideoHistoryGuid");

                            b1.Property<DateTimeOffset>("CreateAt")
                                .HasJsonPropertyName("CreateTime");

                            b1.Property<DateTimeOffset>("UpdateAt")
                                .HasJsonPropertyName("UpdateTime");

                            b1.HasKey("VideoHistoryGuid");

                            b1.ToTable("VideoHistory");

                            b1
                                .ToJson("TimeSpace")
                                .HasColumnType("jsonb");

                            b1.WithOwner()
                                .HasForeignKey("VideoHistoryGuid");
                        });

                    b.Navigation("TimeSpace")
                        .IsRequired();
                });

            modelBuilder.Entity("Video.Domain.Entities.VideoReview", b =>
                {
                    b.HasOne("Video.Domain.Entities.Videos", null)
                        .WithMany("VideoReviews")
                        .HasForeignKey("VideoGuid")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("Video.Domain.Entities.VideoReview", null)
                        .WithMany("VideoReviews")
                        .HasForeignKey("VideoGuid")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.OwnsOne("Video.Domain.ValueObjects.TimeSpace", "TimeSpace", b1 =>
                        {
                            b1.Property<Guid>("VideoReviewGuid");

                            b1.Property<DateTimeOffset>("CreateAt")
                                .HasJsonPropertyName("CreateTime");

                            b1.Property<DateTimeOffset>("UpdateAt")
                                .HasJsonPropertyName("UpdateTime");

                            b1.HasKey("VideoReviewGuid");

                            b1.ToTable("VideoReview");

                            b1
                                .ToJson("TimeSpace")
                                .HasColumnType("jsonb");

                            b1.WithOwner()
                                .HasForeignKey("VideoReviewGuid");
                        });

                    b.OwnsOne("Video.Domain.ValueObjects.VideoControl", "VideoControl", b1 =>
                        {
                            b1.Property<Guid>("VideoReviewGuid");

                            b1.Property<int>("AuthorVideo")
                                .HasJsonPropertyName("AuthorVideo");

                            b1.Property<int>("BarrageControl");

                            b1.Property<bool>("VideoDelete")
                                .HasJsonPropertyName("VideoDelete");

                            b1.Property<bool>("VideoDisplay")
                                .HasJsonPropertyName("VideoDisplay");

                            b1.HasKey("VideoReviewGuid");

                            b1.ToTable("VideoReview");

                            b1
                                .ToJson("VideoControl")
                                .HasColumnType("jsonb");

                            b1.WithOwner()
                                .HasForeignKey("VideoReviewGuid");

                            b1.OwnsOne("Video.Domain.ValueObjects.TimeSpace", "TimeSpace", b2 =>
                                {
                                    b2.Property<Guid>("VideoControlVideoReviewGuid");

                                    b2.Property<DateTimeOffset>("CreateAt")
                                        .HasJsonPropertyName("VideoControlCreateTime");

                                    b2.Property<DateTimeOffset>("UpdateAt")
                                        .HasJsonPropertyName("VideoControlUpdateTime");

                                    b2.HasKey("VideoControlVideoReviewGuid");

                                    b2.ToTable("VideoReview");

                                    b2.WithOwner()
                                        .HasForeignKey("VideoControlVideoReviewGuid");
                                });

                            b1.OwnsOne("Video.Domain.Entities.VideoProtectedTime", "VideoProtectedTime", b2 =>
                                {
                                    b2.Property<Guid>("VideoControlVideoReviewGuid");

                                    b2.Property<DateTimeOffset>("EndTime")
                                        .HasJsonPropertyName("EndTime");

                                    b2.Property<DateTimeOffset>("StartTime")
                                        .HasJsonPropertyName("StartTime");

                                    b2.HasKey("VideoControlVideoReviewGuid");

                                    b2.ToTable("VideoReview");

                                    b2.WithOwner()
                                        .HasForeignKey("VideoControlVideoReviewGuid");
                                });

                            b1.Navigation("TimeSpace")
                                .IsRequired();

                            b1.Navigation("VideoProtectedTime");
                        });

                    b.OwnsMany("Video.Domain.ValueObjects.VideoImage", "VideoImages", b1 =>
                        {
                            b1.Property<Guid>("VideoReviewGuid");

                            b1.Property<int>("__synthesizedOrdinal")
                                .ValueGeneratedOnAdd();

                            b1.Property<string>("Description");

                            b1.Property<long?>("FileSize");

                            b1.Property<string>("Format")
                                .HasMaxLength(16);

                            b1.Property<int?>("Height");

                            b1.Property<string>("ImageUrl")
                                .IsRequired();

                            b1.Property<int>("SortOrder");

                            b1.Property<string>("ThumbnailUrl");

                            b1.Property<int?>("Width");

                            b1.HasKey("VideoReviewGuid", "__synthesizedOrdinal");

                            b1.ToTable("VideoReview");

                            b1
                                .ToJson("VideoImages")
                                .HasColumnType("jsonb");

                            b1.WithOwner()
                                .HasForeignKey("VideoReviewGuid");
                        });

                    b.OwnsOne("Video.Domain.ValueObjects.ReviewContent", "Content", b1 =>
                        {
                            b1.Property<Guid>("VideoReviewGuid");

                            b1.Property<string>("Body")
                                .HasMaxLength(10000)
                                .HasJsonPropertyName("ReviewBody");

                            b1.Property<string>("ContentType")
                                .IsRequired()
                                .HasMaxLength(20)
                                .HasJsonPropertyName("ContentType");

                            b1.HasKey("VideoReviewGuid");

                            b1.ToTable("VideoReview");

                            b1
                                .ToJson("Content")
                                .HasColumnType("jsonb");

                            b1.WithOwner()
                                .HasForeignKey("VideoReviewGuid");

                            b1.OwnsMany("Video.Domain.ValueObjects.VideoImage", "MediaItems", b2 =>
                                {
                                    b2.Property<Guid>("ReviewContentVideoReviewGuid");

                                    b2.Property<int>("__synthesizedOrdinal")
                                        .ValueGeneratedOnAdd();

                                    b2.Property<string>("Description");

                                    b2.Property<string>("ImageUrl")
                                        .IsRequired();

                                    b2.Property<int>("SortOrder");

                                    b2.HasKey("ReviewContentVideoReviewGuid", "__synthesizedOrdinal");

                                    b2.ToTable("VideoReview");

                                    b2.WithOwner()
                                        .HasForeignKey("ReviewContentVideoReviewGuid");
                                });

                            b1.Navigation("MediaItems");
                        });

                    b.OwnsOne("Video.Domain.ValueObjects.ReviewQuote", "Quote", b1 =>
                        {
                            b1.Property<Guid>("VideoReviewGuid");

                            b1.Property<long>("Dislike")
                                .HasJsonPropertyName("c_Dislike");

                            b1.Property<long>("Like")
                                .HasJsonPropertyName("c_Like");

                            b1.HasKey("VideoReviewGuid");

                            b1.ToTable("VideoReview");

                            b1
                                .ToJson("Quote")
                                .HasColumnType("jsonb");

                            b1.WithOwner()
                                .HasForeignKey("VideoReviewGuid");
                        });

                    b.Navigation("Content")
                        .IsRequired();

                    b.Navigation("Quote")
                        .IsRequired();

                    b.Navigation("TimeSpace")
                        .IsRequired();

                    b.Navigation("VideoControl")
                        .IsRequired();

                    b.Navigation("VideoImages");
                });

            modelBuilder.Entity("Video.Domain.Entities.Videos", b =>
                {
                    b.OwnsOne("Video.Domain.ValueObjects.TimeSpace", "TimeSpace", b1 =>
                        {
                            b1.Property<Guid>("VideosVideoGuid");

                            b1.Property<DateTimeOffset>("CreateAt")
                                .HasJsonPropertyName("CreateTime");

                            b1.Property<DateTimeOffset>("UpdateAt")
                                .HasJsonPropertyName("UpdateTime");

                            b1.HasKey("VideosVideoGuid");

                            b1.ToTable("Video");

                            b1
                                .ToJson("TimeSpace")
                                .HasColumnType("jsonb");

                            b1.WithOwner()
                                .HasForeignKey("VideosVideoGuid");
                        });

                    b.OwnsOne("Video.Domain.ValueObjects.VideoControl", "VideoControl", b1 =>
                        {
                            b1.Property<Guid>("VideosVideoGuid");

                            b1.Property<int>("AuthorVideo")
                                .HasJsonPropertyName("AuthorVideo");

                            b1.Property<int>("BarrageControl");

                            b1.Property<bool>("VideoDelete")
                                .HasJsonPropertyName("VideoDelete");

                            b1.Property<bool>("VideoDisplay")
                                .HasJsonPropertyName("VideoDisplay");

                            b1.HasKey("VideosVideoGuid");

                            b1.ToTable("Video");

                            b1
                                .ToJson("VideoControl")
                                .HasColumnType("jsonb");

                            b1.WithOwner()
                                .HasForeignKey("VideosVideoGuid");

                            b1.OwnsOne("Video.Domain.ValueObjects.TimeSpace", "TimeSpace", b2 =>
                                {
                                    b2.Property<Guid>("VideoControlVideosVideoGuid");

                                    b2.Property<DateTimeOffset>("CreateAt")
                                        .HasJsonPropertyName("VideoControlCreateTime");

                                    b2.Property<DateTimeOffset>("UpdateAt")
                                        .HasJsonPropertyName("VideoControlUpdateTime");

                                    b2.HasKey("VideoControlVideosVideoGuid");

                                    b2.ToTable("Video");

                                    b2.WithOwner()
                                        .HasForeignKey("VideoControlVideosVideoGuid");
                                });

                            b1.OwnsOne("Video.Domain.Entities.VideoProtectedTime", "VideoProtectedTime", b2 =>
                                {
                                    b2.Property<Guid>("VideoControlVideosVideoGuid");

                                    b2.Property<DateTimeOffset>("EndTime")
                                        .HasJsonPropertyName("VideoProtectedEndTime");

                                    b2.Property<DateTimeOffset>("StartTime")
                                        .HasJsonPropertyName("VideoProtectedStartTime");

                                    b2.HasKey("VideoControlVideosVideoGuid");

                                    b2.ToTable("Video");

                                    b2.WithOwner()
                                        .HasForeignKey("VideoControlVideosVideoGuid");
                                });

                            b1.Navigation("TimeSpace")
                                .IsRequired();

                            b1.Navigation("VideoProtectedTime");
                        });

                    b.OwnsOne("Video.Domain.ValueObjects.VideoQuote", "VideoQuote", b1 =>
                        {
                            b1.Property<Guid>("VideosVideoGuid");

                            b1.Property<long>("Ballot")
                                .HasJsonPropertyName("v_Ballot");

                            b1.Property<long>("Down")
                                .HasJsonPropertyName("v_Down");

                            b1.Property<long>("Share")
                                .HasJsonPropertyName("v_Share");

                            b1.Property<long>("Stars")
                                .HasJsonPropertyName("v_Stars");

                            b1.Property<long>("Upvote")
                                .HasJsonPropertyName("v_Upvote");

                            b1.Property<long>("Watch")
                                .HasJsonPropertyName("v_Watch");

                            b1.HasKey("VideosVideoGuid");

                            b1.ToTable("Video");

                            b1
                                .ToJson("VideoQuote")
                                .HasColumnType("jsonb");

                            b1.WithOwner()
                                .HasForeignKey("VideosVideoGuid");
                        });

                    b.Navigation("TimeSpace")
                        .IsRequired();

                    b.Navigation("VideoControl")
                        .IsRequired();

                    b.Navigation("VideoQuote")
                        .IsRequired();
                });

            modelBuilder.Entity("Video.Domain.Entities.VideoReview", b =>
                {
                    b.Navigation("VideoReviews");
                });

            modelBuilder.Entity("Video.Domain.Entities.Videos", b =>
                {
                    b.Navigation("VideoBarrageList");

                    b.Navigation("VideoReviews");
                });
#pragma warning restore 612, 618
        }
    }
}
