<Project Sdk="Microsoft.NET.Sdk.Web">

    <PropertyGroup>
        <TargetFramework>net9.0</TargetFramework>
        <Nullable>enable</Nullable>
        <ImplicitUsings>enable</ImplicitUsings>
        <UserSecretsId>15c2b131-aa6e-4cca-a28e-a1b26190e056</UserSecretsId>
    </PropertyGroup>

    <ItemGroup>
      <Compile Remove="Application\CommandHandler\**" />
      <Content Remove="Application\CommandHandler\**" />
      <EmbeddedResource Remove="Application\CommandHandler\**" />
      <None Remove="Application\CommandHandler\**" />
    </ItemGroup>

    <ItemGroup>
        <PackageReference Include="MailKit" Version="4.13.0" />
        <PackageReference Include="Microsoft.AspNetCore.OpenApi" Version="9.0.9" />
        <PackageReference Include="Microsoft.EntityFrameworkCore" Version="9.0.9" />
        <PackageReference Include="Microsoft.EntityFrameworkCore.Tools" Version="9.0.9">
            <PrivateAssets>all</PrivateAssets>
            <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
        </PackageReference>
        <PackageReference Include="Microsoft.Extensions.DependencyInjection.Abstractions" Version="9.0.9" />
        <PackageReference Include="NotMediator" Version="1.0.5" />
        <PackageReference Include="Scalar.AspNetCore" Version="2.8.1" />
    </ItemGroup>

    <ItemGroup>
        <ProjectReference Include="..\CommonsInitializer\CommonsInitializer.csproj" />
        <ProjectReference Include="..\DomainCommon\DomainCommon.csproj" />
        <ProjectReference Include="..\Identity.Domain\Identity.Domain.csproj" />
        <ProjectReference Include="..\Identity.Infrastructres\Identity.Infrastructure.csproj" />
        <ProjectReference Include="..\JWToken\Token.JWT.csproj" />
    </ItemGroup>

</Project>
