<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net9.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="MailKit" Version="4.7.1.1"/>
        <PackageReference Include="Microsoft.Extensions.Configuration.Abstractions" Version="8.0.0"/>
        <PackageReference Include="Microsoft.Extensions.Options" Version="8.0.0"/>
    </ItemGroup>

    <ItemGroup>
        <ProjectReference Include="..\DomainCommonst\DomainCommonst.csproj"/>
        <ProjectReference Include="..\Evenbus\Evenbus.csproj"/>
    </ItemGroup>

</Project>
