// <auto-generated />
using System;
using Identity.Infrastructure.EntityFramework;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Identity.Infrastructure.Migrations
{
    [DbContext(typeof(IdentityDbContext))]
    [Migration("20250802174907_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("Identity")
                .HasAnnotation("ProductVersion", "9.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.HasSequence("Author2seq")
                .IncrementsBy(10);

            modelBuilder.HasSequence("NotClientseq")
                .IncrementsBy(10);

            modelBuilder.HasSequence("RoleClaimseq")
                .IncrementsBy(10);

            modelBuilder.HasSequence("Roleseq")
                .IncrementsBy(10);

            modelBuilder.HasSequence("UserAccessFailseq")
                .IncrementsBy(10);

            modelBuilder.HasSequence("UserSafarseq")
                .IncrementsBy(10);

            modelBuilder.HasSequence("Userseq")
                .IncrementsBy(10);

            modelBuilder.Entity("Identity.Domain.AggregatesModel.Author2Aggregate.Author2", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseHiLo(b.Property<int>("Id"), "Author2seq");

                    b.Property<Guid>("Author2Guid")
                        .HasColumnType("uuid");

                    b.Property<string>("AuthorDescription")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("AuthorName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("AuthorPrivateKey")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("AuthorSecret")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Author2", "Identity");
                });

            modelBuilder.Entity("Identity.Domain.AggregatesModel.ClientAggregate.NotClient", b =>
                {
                    b.Property<Guid>("NotClientId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("client_guid");

                    b.Property<int>("Id")
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseHiLo(b.Property<int>("Id"), "NotClientseq");

                    b.Property<string>("NotClientDescription")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("NotClientName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("NotClientPrivateKey")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("NotClientSecret")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("NotClientType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("NotClientUri")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("NotClientId");

                    b.ToTable("NotClient", "Identity");
                });

            modelBuilder.Entity("Identity.Domain.AggregatesModel.RoleAggregate.RoleClaim", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseHiLo(b.Property<int>("Id"), "RoleClaimseq");

                    b.Property<string>("ClaimType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ClaimValue")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("RoleGuid")
                        .HasColumnType("uuid");

                    b.Property<int?>("RolesId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("RolesId");

                    b.ToTable("RoleClaims", "Identity");
                });

            modelBuilder.Entity("Identity.Domain.AggregatesModel.RoleAggregate.Roles", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseHiLo(b.Property<int>("Id"), "Roleseq");

                    b.Property<string>("Attribute")
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("CreateRoleTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("RoleAuthority")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<Guid>("RoleGuid")
                        .HasColumnType("uuid");

                    b.Property<string>("RoleName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("RoleStatus")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("Id");

                    b.ToTable("Role", "Identity");
                });

            modelBuilder.Entity("Identity.Domain.AggregatesModel.UserAggregate.User", b =>
                {
                    b.Property<Guid>("UserGuid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("UserGuid");

                    b.Property<DateTimeOffset>("CreateDatetime")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("CreateDateTime");

                    b.Property<int>("Id")
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseHiLo(b.Property<int>("Id"), "Userseq");

                    b.Property<string>("ImageCover")
                        .HasColumnType("text")
                        .HasColumnName("ImageCover");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("PasswordHash");

                    b.Property<string>("UserEmail")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("UserName")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("UserName");

                    b.Property<Guid>("UserRoleGuid")
                        .HasColumnType("uuid")
                        .HasColumnName("UserRoleGuid");

                    b.HasKey("UserGuid");

                    b.HasIndex("UserEmail")
                        .HasDatabaseName("IX_User_UserGuid_UserEmail_UserPhone");

                    b.ToTable("User", "Identity");
                });

            modelBuilder.Entity("Identity.Domain.AggregatesModel.UserAggregate.UserAccessFail", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseHiLo(b.Property<int>("Id"), "UserAccessFailseq");

                    b.Property<int>("AccessFaildCount")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset?>("LockOutEnd")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("UserAccessFailGuid")
                        .HasColumnType("uuid");

                    b.Property<Guid>("UserGuid")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("UserGuid")
                        .IsUnique();

                    b.ToTable("UserAccessFail", "Identity");
                });

            modelBuilder.Entity("Identity.Domain.AggregatesModel.UserAggregate.UserClaim", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ClaimValue")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("UserClaimGuid")
                        .HasColumnType("uuid");

                    b.Property<Guid>("UserGuid")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("UserGuid");

                    b.ToTable("UserClaims", "Identity");
                });

            modelBuilder.Entity("Identity.Domain.AggregatesModel.UserAggregate.UserSafety", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseHiLo(b.Property<int>("Id"), "UserSafarseq");

                    b.Property<int>("BlackOrWhite")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset?>("LockOutEnd")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("PasswordSalt")
                        .HasColumnType("text");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("text");

                    b.Property<Guid>("UserGuid")
                        .HasColumnType("uuid")
                        .HasColumnName("user_guid");

                    b.Property<Guid>("UserSafetyGuid")
                        .HasColumnType("uuid");

                    b.Property<int>("UserStatus")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("UserGuid")
                        .IsUnique();

                    b.ToTable("UserSafety", "Identity");
                });

            modelBuilder.Entity("Identity.Domain.Entities.PhoneNumber", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<long>("AddressRegion")
                        .HasColumnType("bigint");

                    b.Property<string>("PhoneCode")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("UserGuid")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("UserGuid")
                        .IsUnique();

                    b.ToTable("PhoneNumber", "Identity");
                });

            modelBuilder.Entity("Identity.Domain.AggregatesModel.RoleAggregate.RoleClaim", b =>
                {
                    b.HasOne("Identity.Domain.AggregatesModel.RoleAggregate.Roles", null)
                        .WithMany("RoleClaims")
                        .HasForeignKey("RolesId");
                });

            modelBuilder.Entity("Identity.Domain.AggregatesModel.UserAggregate.User", b =>
                {
                    b.OwnsOne("Identity.Domain.AggregatesModel.UserAggregate.Address", "UserAddress", b1 =>
                        {
                            b1.Property<Guid>("UserGuid")
                                .HasColumnType("uuid");

                            b1.Property<string>("City")
                                .IsRequired()
                                .HasColumnType("text");

                            b1.Property<string>("Country")
                                .IsRequired()
                                .HasColumnType("text");

                            b1.Property<string>("Detail")
                                .IsRequired()
                                .HasColumnType("text");

                            b1.Property<string>("District")
                                .IsRequired()
                                .HasColumnType("text");

                            b1.Property<string>("Province")
                                .IsRequired()
                                .HasColumnType("text");

                            b1.Property<string>("Street")
                                .IsRequired()
                                .HasColumnType("text");

                            b1.HasKey("UserGuid");

                            b1.ToTable("User", "Identity");

                            b1.WithOwner()
                                .HasForeignKey("UserGuid");
                        });

                    b.Navigation("UserAddress");
                });

            modelBuilder.Entity("Identity.Domain.AggregatesModel.UserAggregate.UserAccessFail", b =>
                {
                    b.HasOne("Identity.Domain.AggregatesModel.UserAggregate.User", null)
                        .WithOne("UserAccessFail")
                        .HasForeignKey("Identity.Domain.AggregatesModel.UserAggregate.UserAccessFail", "UserGuid")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Identity.Domain.AggregatesModel.UserAggregate.UserClaim", b =>
                {
                    b.HasOne("Identity.Domain.AggregatesModel.UserAggregate.User", null)
                        .WithMany("UserClaimsReadOnly")
                        .HasForeignKey("UserGuid")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();
                });

            modelBuilder.Entity("Identity.Domain.AggregatesModel.UserAggregate.UserSafety", b =>
                {
                    b.HasOne("Identity.Domain.AggregatesModel.UserAggregate.User", null)
                        .WithOne("UserSafety")
                        .HasForeignKey("Identity.Domain.AggregatesModel.UserAggregate.UserSafety", "UserGuid")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Identity.Domain.Entities.PhoneNumber", b =>
                {
                    b.HasOne("Identity.Domain.AggregatesModel.UserAggregate.User", null)
                        .WithOne("PhoneNumber")
                        .HasForeignKey("Identity.Domain.Entities.PhoneNumber", "UserGuid")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Identity.Domain.AggregatesModel.RoleAggregate.Roles", b =>
                {
                    b.Navigation("RoleClaims");
                });

            modelBuilder.Entity("Identity.Domain.AggregatesModel.UserAggregate.User", b =>
                {
                    b.Navigation("PhoneNumber");

                    b.Navigation("UserAccessFail")
                        .IsRequired();

                    b.Navigation("UserClaimsReadOnly");

                    b.Navigation("UserSafety")
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
