// <auto-generated />
using System;
using System.Collections.Generic;
using Identity.Infrastructure.EntityFramework;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Identity.Infrastructure.Migrations
{
    [DbContext(typeof(IdentityDbContext))]
    [Migration("20260705193124_BlogIdentity")]
    partial class BlogIdentity
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.HasSequence("NotClientseq")
                .IncrementsBy(10);

            modelBuilder.HasSequence("UserAccessFailseq")
                .IncrementsBy(10);

            modelBuilder.HasSequence("UserSafarseq")
                .IncrementsBy(10);

            modelBuilder.HasSequence("Userseq")
                .IncrementsBy(10);

            modelBuilder.Entity("GroupPermissions", b =>
                {
                    b.Property<int>("PermissionGuid")
                        .HasColumnType("integer");

                    b.Property<Guid>("RoleGroupGuid")
                        .HasColumnType("uuid");

                    b.HasKey("PermissionGuid", "RoleGroupGuid");

                    b.HasIndex("RoleGroupGuid");

                    b.ToTable("GroupPermissions");
                });

            modelBuilder.Entity("Identity.Domain.Entities.ClientAggregate.NotClient", b =>
                {
                    b.Property<Guid>("NotClientId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("client_guid");

                    b.Property<int>("Id")
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseHiLo(b.Property<int>("Id"), "NotClientseq");

                    b.Property<string>("NotClientDescription")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("NotClientName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("NotClientPrivateKey")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("NotClientSecret")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("NotClientType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("NotClientUri")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("NotClientId");

                    b.ToTable("NotClient", (string)null);
                });

            modelBuilder.Entity("Identity.Domain.Entities.RoleAggregate.Permission", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ApiMethod")
                        .HasColumnType("text");

                    b.Property<string>("ApiUrl")
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<string>("MenuPath")
                        .HasColumnType("text");

                    b.Property<string>("PermissionCode")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("PermissionId")
                        .HasColumnType("uuid");

                    b.Property<string>("PermissionName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PermissionType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Permission");
                });

            modelBuilder.Entity("Identity.Domain.Entities.RoleAggregate.RoleGroup", b =>
                {
                    b.Property<Guid>("RoleGroupGuid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<DateTimeOffset>("CreatedRoleGroup")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Id")
                        .HasColumnType("integer");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<string>("RoleGroupCode")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("RoleGroupName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("RoleGroupGuid");

                    b.ToTable("RoleGroups", (string)null);
                });

            modelBuilder.Entity("Identity.Domain.Entities.RoleAggregate.Roles", b =>
                {
                    b.Property<Guid>("RoleGuid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<string>("Attribute")
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("CreateRole")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Id")
                        .HasColumnType("integer");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<string>("RoleAuthority")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("RoleCode")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("RoleName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("RoleStatus")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("RoleGuid");

                    b.ToTable("Roles", (string)null);
                });

            modelBuilder.Entity("Identity.Domain.Entities.UserAggregate.PhoneNumber", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<long>("AddressRegion")
                        .HasColumnType("bigint");

                    b.Property<string>("PhoneCode")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("UserGuid")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("UserGuid")
                        .IsUnique();

                    b.ToTable("PhoneNumber");
                });

            modelBuilder.Entity("Identity.Domain.Entities.UserAggregate.User", b =>
                {
                    b.Property<Guid>("UserGuid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("user_guid");

                    b.PrimitiveCollection<HashSet<Guid>>("AuthorGuids")
                        .IsRequired()
                        .HasColumnType("uuid[]");

                    b.Property<DateTimeOffset>("CreateDatetime")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("create_datetime");

                    b.Property<int>("Id")
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseHiLo(b.Property<int>("Id"), "Userseq");

                    b.Property<string>("ImageCover")
                        .HasColumnType("text")
                        .HasColumnName("image_cover");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("password_hash");

                    b.Property<string>("UserEmail")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("user_name");

                    b.PrimitiveCollection<HashSet<Guid>>("UserRoleGuid")
                        .IsRequired()
                        .HasColumnType("uuid[]")
                        .HasColumnName("user_role_guid");

                    b.HasKey("UserGuid");

                    b.ToTable("User", (string)null);
                });

            modelBuilder.Entity("Identity.Domain.Entities.UserAggregate.UserAccessFail", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseHiLo(b.Property<int>("Id"), "UserAccessFailseq");

                    b.Property<int>("AccessFaildCount")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset?>("LockOutEnd")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("UserAccessFailGuid")
                        .HasColumnType("uuid");

                    b.Property<Guid>("UserGuid")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("UserGuid")
                        .IsUnique();

                    b.ToTable("UserAccessFail", (string)null);
                });

            modelBuilder.Entity("Identity.Domain.Entities.UserAggregate.UserSafety", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseHiLo(b.Property<int>("Id"), "UserSafarseq");

                    b.Property<int>("BlackOrWhite")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset?>("LockOutEnd")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("PasswordSalt")
                        .HasColumnType("text");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("text");

                    b.Property<Guid>("UserGuid")
                        .HasColumnType("uuid")
                        .HasColumnName("user_guid");

                    b.Property<Guid>("UserSafetyGuid")
                        .HasColumnType("uuid");

                    b.Property<int>("UserStatus")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("UserGuid")
                        .IsUnique();

                    b.ToTable("UserSafety", (string)null);
                });

            modelBuilder.Entity("Identity.Domain.Entities.UserExternalLoginAggregate.UserExternalLogin", b =>
                {
                    b.Property<Guid>("LoginId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("EncryptedAccessToken")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<string>("EncryptedRefreshToken")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<DateTimeOffset>("LastUsedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Provider")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("ProviderDisplayName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("ProviderKey")
                        .IsRequired()
                        .HasMaxLength(450)
                        .HasColumnType("character varying(450)");

                    b.Property<string>("ProviderUnionId")
                        .HasMaxLength(450)
                        .HasColumnType("character varying(450)");

                    b.Property<DateTimeOffset?>("TokenExpiresAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("LoginId");

                    b.HasIndex("UserId");

                    b.HasIndex("Provider", "ProviderKey")
                        .IsUnique();

                    b.ToTable("UserExternalLogins", (string)null);
                });

            modelBuilder.Entity("RoleGroupRoles", b =>
                {
                    b.Property<Guid>("RoleGroupGuid")
                        .HasColumnType("uuid");

                    b.Property<Guid>("RoleGuid")
                        .HasColumnType("uuid");

                    b.HasKey("RoleGroupGuid", "RoleGuid");

                    b.HasIndex("RoleGuid");

                    b.ToTable("RoleGroupRoles");
                });

            modelBuilder.Entity("RolePermissions", b =>
                {
                    b.Property<int>("PermissionGuid")
                        .HasColumnType("integer");

                    b.Property<Guid>("RoleGuid")
                        .HasColumnType("uuid");

                    b.HasKey("PermissionGuid", "RoleGuid");

                    b.HasIndex("RoleGuid");

                    b.ToTable("RolePermissions");
                });

            modelBuilder.Entity("GroupPermissions", b =>
                {
                    b.HasOne("Identity.Domain.Entities.RoleAggregate.Permission", null)
                        .WithMany()
                        .HasForeignKey("PermissionGuid")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Identity.Domain.Entities.RoleAggregate.RoleGroup", null)
                        .WithMany()
                        .HasForeignKey("RoleGroupGuid")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Identity.Domain.Entities.UserAggregate.PhoneNumber", b =>
                {
                    b.HasOne("Identity.Domain.Entities.UserAggregate.User", null)
                        .WithOne("PhoneNumber")
                        .HasForeignKey("Identity.Domain.Entities.UserAggregate.PhoneNumber", "UserGuid")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Identity.Domain.Entities.UserAggregate.User", b =>
                {
                    b.OwnsOne("Identity.Domain.Entities.UserAggregate.Address", "UserAddress", b1 =>
                        {
                            b1.Property<Guid>("UserGuid")
                                .HasColumnType("uuid");

                            b1.Property<string>("City")
                                .IsRequired()
                                .HasColumnType("text");

                            b1.Property<string>("Country")
                                .IsRequired()
                                .HasColumnType("text");

                            b1.Property<string>("Detail")
                                .IsRequired()
                                .HasColumnType("text");

                            b1.Property<string>("District")
                                .IsRequired()
                                .HasColumnType("text");

                            b1.Property<string>("Province")
                                .IsRequired()
                                .HasColumnType("text");

                            b1.Property<string>("Street")
                                .IsRequired()
                                .HasColumnType("text");

                            b1.HasKey("UserGuid");

                            b1.ToTable("User");

                            b1.WithOwner()
                                .HasForeignKey("UserGuid");
                        });

                    b.Navigation("UserAddress");
                });

            modelBuilder.Entity("Identity.Domain.Entities.UserAggregate.UserAccessFail", b =>
                {
                    b.HasOne("Identity.Domain.Entities.UserAggregate.User", null)
                        .WithOne("UserAccessFail")
                        .HasForeignKey("Identity.Domain.Entities.UserAggregate.UserAccessFail", "UserGuid")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Identity.Domain.Entities.UserAggregate.UserSafety", b =>
                {
                    b.HasOne("Identity.Domain.Entities.UserAggregate.User", null)
                        .WithOne("UserSafety")
                        .HasForeignKey("Identity.Domain.Entities.UserAggregate.UserSafety", "UserGuid")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("RoleGroupRoles", b =>
                {
                    b.HasOne("Identity.Domain.Entities.RoleAggregate.RoleGroup", null)
                        .WithMany()
                        .HasForeignKey("RoleGroupGuid")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Identity.Domain.Entities.RoleAggregate.Roles", null)
                        .WithMany()
                        .HasForeignKey("RoleGuid")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("RolePermissions", b =>
                {
                    b.HasOne("Identity.Domain.Entities.RoleAggregate.Permission", null)
                        .WithMany()
                        .HasForeignKey("PermissionGuid")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Identity.Domain.Entities.RoleAggregate.Roles", null)
                        .WithMany()
                        .HasForeignKey("RoleGuid")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Identity.Domain.Entities.UserAggregate.User", b =>
                {
                    b.Navigation("PhoneNumber");

                    b.Navigation("UserAccessFail")
                        .IsRequired();

                    b.Navigation("UserSafety")
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
