// <auto-generated />
using System;
using Identity.Infrastructure.EntityFramework;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Identity.Infrastructure.Migrations
{
    [DbContext(typeof(IdentityDbContext))]
    partial class IdentityDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Identity.Domain.AggregatesModel.Author2Aggregate.Author2", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("AuthorDescription")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("AuthorName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("AuthorPrivateKey")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("AuthorSecret")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("UserGuid")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.ToTable("Author2", (string)null);
                });

            modelBuilder.Entity("Identity.Domain.AggregatesModel.ClientAggregate.NotClient", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("NotClientDescription")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("NotClientName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("NotClientPrivateKey")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("NotClientSecret")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("NotClientType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("NotClientUri")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("UserGuid")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.ToTable("NotClient", (string)null);
                });

            modelBuilder.Entity("Identity.Domain.AggregatesModel.RoleAggregate.RoleClaim", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("ClaimType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ClaimValue")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("RoleGuid")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("RolesId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("RolesId");

                    b.ToTable("RoleClaims", (string)null);
                });

            modelBuilder.Entity("Identity.Domain.AggregatesModel.RoleAggregate.Roles", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Attribute")
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("CreateRoleTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("RoleAuthority")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("RoleName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("RoleStatus")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("Id");

                    b.ToTable("Role", (string)null);
                });

            modelBuilder.Entity("Identity.Domain.AggregatesModel.UserAggregate.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Address")
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("CreateDatetime")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("CreateDateTime");

                    b.Property<string>("ImageCover")
                        .HasColumnType("text")
                        .HasColumnName("ImageCover");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("PasswordHash");

                    b.Property<string>("UserEmail")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("UserName")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("UserName");

                    b.Property<Guid>("UserRoleGuid")
                        .HasColumnType("uuid")
                        .HasColumnName("UserRoleGuid");

                    b.HasKey("Id");

                    b.HasIndex("UserEmail")
                        .HasDatabaseName("IX_User_UserGuid_UserEmail_UserPhone");

                    b.ToTable("User", (string)null);
                });

            modelBuilder.Entity("Identity.Domain.AggregatesModel.UserAggregate.UserAccessFail", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("AccessFaildCount")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset?>("LockOutEnd")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("UserGuid")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("UserGuid")
                        .IsUnique();

                    b.ToTable("UserAccessFail", (string)null);
                });

            modelBuilder.Entity("Identity.Domain.AggregatesModel.UserAggregate.UserClaim", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("ClaimType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ClaimValue")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("UserGuid")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("UserGuid");

                    b.ToTable("UserClaims", (string)null);
                });

            modelBuilder.Entity("Identity.Domain.AggregatesModel.UserAggregate.UserLoginHistory", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreateDataTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Email")
                        .HasColumnType("text");

                    b.Property<string>("LoginMessage")
                        .HasColumnType("text");

                    b.Property<Guid?>("PhoneNumberId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("UserGuid")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("PhoneNumberId");

                    b.ToTable("UserLoginHistories");
                });

            modelBuilder.Entity("Identity.Domain.AggregatesModel.UserAggregate.UserSafety", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("BlackOrWhite")
                        .HasColumnType("integer");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<DateTimeOffset?>("LockOutEnd")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("PasswordSalt")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("SecurityStamp")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("UserGuid")
                        .HasColumnType("uuid");

                    b.Property<int>("UserStatus")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("UserGuid")
                        .IsUnique();

                    b.ToTable("UserSafety", (string)null);
                });

            modelBuilder.Entity("Identity.Domain.Entities.PhoneNumber", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<long>("AddressRegion")
                        .HasColumnType("bigint");

                    b.Property<string>("PhoneCode")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("UserGuid")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("UserGuid")
                        .IsUnique();

                    b.ToTable("PhoneNumber");
                });

            modelBuilder.Entity("Identity.Infrastructure.RequestManager.ClientRequest", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("Time")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.ToTable("ClientRequests", (string)null);
                });

            modelBuilder.Entity("Identity.Domain.AggregatesModel.RoleAggregate.RoleClaim", b =>
                {
                    b.HasOne("Identity.Domain.AggregatesModel.RoleAggregate.Roles", null)
                        .WithMany("RoleClaims")
                        .HasForeignKey("RolesId");
                });

            modelBuilder.Entity("Identity.Domain.AggregatesModel.UserAggregate.UserAccessFail", b =>
                {
                    b.HasOne("Identity.Domain.AggregatesModel.UserAggregate.User", null)
                        .WithOne("UserAccessFail")
                        .HasForeignKey("Identity.Domain.AggregatesModel.UserAggregate.UserAccessFail", "UserGuid")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Identity.Domain.AggregatesModel.UserAggregate.UserClaim", b =>
                {
                    b.HasOne("Identity.Domain.AggregatesModel.UserAggregate.User", null)
                        .WithMany("UserClaimsReadOnly")
                        .HasForeignKey("UserGuid")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Identity.Domain.AggregatesModel.UserAggregate.UserLoginHistory", b =>
                {
                    b.HasOne("Identity.Domain.Entities.PhoneNumber", "PhoneNumber")
                        .WithMany()
                        .HasForeignKey("PhoneNumberId");

                    b.Navigation("PhoneNumber");
                });

            modelBuilder.Entity("Identity.Domain.AggregatesModel.UserAggregate.UserSafety", b =>
                {
                    b.HasOne("Identity.Domain.AggregatesModel.UserAggregate.User", null)
                        .WithOne("UserSafety")
                        .HasForeignKey("Identity.Domain.AggregatesModel.UserAggregate.UserSafety", "UserGuid")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Identity.Domain.Entities.PhoneNumber", b =>
                {
                    b.HasOne("Identity.Domain.AggregatesModel.UserAggregate.User", null)
                        .WithOne("PhoneNumber")
                        .HasForeignKey("Identity.Domain.Entities.PhoneNumber", "UserGuid")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Identity.Domain.AggregatesModel.RoleAggregate.Roles", b =>
                {
                    b.Navigation("RoleClaims");
                });

            modelBuilder.Entity("Identity.Domain.AggregatesModel.UserAggregate.User", b =>
                {
                    b.Navigation("PhoneNumber");

                    b.Navigation("UserAccessFail")
                        .IsRequired();

                    b.Navigation("UserClaimsReadOnly");

                    b.Navigation("UserSafety")
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
