// <auto-generated />
using System;
using System.Collections.Generic;
using Identity.Infrastructure.EntityFramework;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Identity.Infrastructure.Migrations
{
    [DbContext(typeof(IdentityDbContext))]
    partial class IdentityDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Identity.Domain.Entities.ClientAggregate.NotClient", b =>
                {
                    b.Property<Guid>("NotClientId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("client_guid");

                    b.PrimitiveCollection<HashSet<string>>("AllowedCorsOrigins")
                        .HasColumnType("text[]")
                        .HasColumnName("allowed_cors_origins");

                    b.PrimitiveCollection<HashSet<string>>("AllowedGrantTypes")
                        .IsRequired()
                        .HasColumnType("text[]")
                        .HasColumnName("allowed_grant_types");

                    b.PrimitiveCollection<HashSet<string>>("AllowedScopes")
                        .IsRequired()
                        .HasColumnType("text[]")
                        .HasColumnName("allowed_scopes");

                    b.Property<string>("ApplicationDescription")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("application_description");

                    b.Property<string>("ApplicationIcon")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("application_icon");

                    b.Property<string>("ApplicationName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("application_name");

                    b.Property<string>("ApplicationType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("application_type");

                    b.Property<string>("ClientId")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("client_id");

                    b.Property<string>("ClientSecret")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("client_secret");

                    b.Property<string>("ContactEmail")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("contact_email");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("HomepageUri")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("homepage_uri");

                    b.PrimitiveCollection<HashSet<string>>("PostLogoutRedirectUris")
                        .IsRequired()
                        .HasColumnType("text[]")
                        .HasColumnName("post_logout_redirect_uris");

                    b.Property<string>("PrivacyPolicyUri")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("privacy_policy_uri");

                    b.PrimitiveCollection<HashSet<string>>("RedirectUris")
                        .IsRequired()
                        .HasColumnType("text[]")
                        .HasColumnName("redirect_uris");

                    b.Property<bool>("RequireConsent")
                        .HasColumnType("boolean")
                        .HasColumnName("require_consent");

                    b.Property<bool>("RequirePkce")
                        .HasColumnType("boolean")
                        .HasColumnName("require_pkce");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("status");

                    b.Property<string>("TermsOfServiceUri")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("terms_of_service_uri");

                    b.Property<string>("TokenEndpointAuthMethod")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("token_endpoint_auth_method");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("NotClientId");

                    b.HasIndex("ClientId")
                        .IsUnique();

                    b.ToTable("NotClient", (string)null);
                });

            modelBuilder.Entity("Identity.Domain.Entities.RoleAggregate.Permission", b =>
                {
                    b.Property<Guid>("PermissionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("ApiMethod")
                        .HasColumnType("text");

                    b.Property<string>("ApiUrl")
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<string>("MenuPath")
                        .HasColumnType("text");

                    b.Property<string>("PermissionCode")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PermissionName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PermissionType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("PermissionId");

                    b.ToTable("Permissions", (string)null);
                });

            modelBuilder.Entity("Identity.Domain.Entities.RoleAggregate.RoleGroup", b =>
                {
                    b.Property<Guid>("RoleGroupGuid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<DateTimeOffset>("CreatedRoleGroup")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<string>("RoleGroupCode")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("RoleGroupName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.PrimitiveCollection<List<Guid>>("RoleGuids")
                        .IsRequired()
                        .HasColumnType("uuid[]")
                        .HasColumnName("role_guids");

                    b.HasKey("RoleGroupGuid");

                    b.ToTable("RoleGroups", (string)null);
                });

            modelBuilder.Entity("Identity.Domain.Entities.RoleAggregate.Roles", b =>
                {
                    b.Property<Guid>("RoleGuid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<string>("Attribute")
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("CreateRole")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<string>("RoleAuthority")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("RoleCode")
                        .IsRequired()
                        .HasColumnType("text");

                    b.PrimitiveCollection<List<Guid>>("RoleGroupGuids")
                        .IsRequired()
                        .HasColumnType("uuid[]")
                        .HasColumnName("role_group_guids");

                    b.Property<string>("RoleName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("RoleStatus")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.PrimitiveCollection<HashSet<Guid>>("UserGuid")
                        .IsRequired()
                        .HasColumnType("uuid[]");

                    b.HasKey("RoleGuid");

                    b.ToTable("Roles", (string)null);
                });

            modelBuilder.Entity("Identity.Domain.Entities.UserAggregate.User", b =>
                {
                    b.Property<Guid>("UserGuid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("user_guid");

                    b.PrimitiveCollection<List<Guid>>("AuthorGuids")
                        .IsRequired()
                        .HasColumnType("uuid[]");

                    b.Property<string>("AvatarUrl")
                        .HasColumnType("text")
                        .HasColumnName("avatar_url");

                    b.Property<DateTimeOffset>("CreateDatetime")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("create_datetime");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("password_hash");

                    b.Property<string>("UserEmail")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("user_name");

                    b.PrimitiveCollection<List<Guid>>("UserRoleGuid")
                        .IsRequired()
                        .HasColumnType("uuid[]")
                        .HasColumnName("user_role_guid");

                    b.HasKey("UserGuid");

                    b.HasIndex("UserEmail")
                        .IsUnique();

                    b.ToTable("User", (string)null);
                });

            modelBuilder.Entity("Identity.Domain.Entities.UserAggregate.UserAccessFail", b =>
                {
                    b.Property<Guid>("UserAccessFailGuid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("AccessFaildCount")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset?>("LockOutEnd")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("UserGuid")
                        .HasColumnType("uuid");

                    b.HasKey("UserAccessFailGuid");

                    b.HasIndex("UserGuid")
                        .IsUnique();

                    b.ToTable("UserAccessFail", (string)null);
                });

            modelBuilder.Entity("Identity.Domain.Entities.UserAggregate.UserLoginHistory", b =>
                {
                    b.Property<Guid>("LoginGuid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreateDataTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Email")
                        .HasColumnType("text");

                    b.Property<string>("LoginMessage")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<Guid>("UserGuid")
                        .HasColumnType("uuid");

                    b.HasKey("LoginGuid");

                    b.ToTable("UserLoginHistory", (string)null);
                });

            modelBuilder.Entity("Identity.Domain.Entities.UserAggregate.UserSafety", b =>
                {
                    b.Property<Guid>("UserSafetyGuid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("BlackOrWhite")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset?>("LockOutEnd")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("PasswordSalt")
                        .HasColumnType("text");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("text");

                    b.Property<Guid>("UserGuid")
                        .HasColumnType("uuid")
                        .HasColumnName("user_guid");

                    b.Property<int>("UserStatus")
                        .HasColumnType("integer");

                    b.HasKey("UserSafetyGuid");

                    b.HasIndex("UserGuid")
                        .IsUnique();

                    b.ToTable("UserSafety", (string)null);
                });

            modelBuilder.Entity("Identity.Domain.Entities.UserExternalLoginAggregate.UserExternalLogin", b =>
                {
                    b.Property<Guid>("LoginId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("EncryptedAccessToken")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<string>("EncryptedRefreshToken")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<DateTimeOffset>("LastUsedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Provider")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("ProviderDisplayName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("ProviderKey")
                        .IsRequired()
                        .HasMaxLength(450)
                        .HasColumnType("character varying(450)");

                    b.Property<string>("ProviderUnionId")
                        .HasMaxLength(450)
                        .HasColumnType("character varying(450)");

                    b.Property<DateTimeOffset?>("TokenExpiresAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("LoginId");

                    b.HasIndex("UserId");

                    b.HasIndex("Provider", "ProviderKey")
                        .IsUnique();

                    b.ToTable("UserExternalLogins", (string)null);
                });

            modelBuilder.Entity("Identity.Infrastructure.Idempotent.ClientRequest", b =>
                {
                    b.Property<Guid>("ClientRequestId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("ClientRequestName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("CreatedDate")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("ClientRequestId");

                    b.ToTable("ClientRequest", (string)null);
                });

            modelBuilder.Entity("Notcomd.EventBus.Outbox.OutboxMessage", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<string>("CorrelationId")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("EventData")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<string>("EventType")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("LastError")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<DateTimeOffset?>("NextRetryAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("ProcessCount")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0);

                    b.Property<DateTimeOffset?>("SentAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.HasKey("Id");

                    b.HasIndex("SentAt")
                        .HasDatabaseName("IX_OutboxMessages_SentAt");

                    b.HasIndex("Status", "CreatedAt")
                        .HasDatabaseName("IX_OutboxMessages_Status_CreatedAt");

                    b.ToTable("OutboxMessages", (string)null);
                });

            modelBuilder.Entity("RoleGroupPermissions", b =>
                {
                    b.Property<Guid>("PermissionGuid")
                        .HasColumnType("uuid");

                    b.Property<Guid>("RoleGroupGuid")
                        .HasColumnType("uuid");

                    b.HasKey("PermissionGuid", "RoleGroupGuid");

                    b.HasIndex("RoleGroupGuid");

                    b.ToTable("RoleGroupPermissions");
                });

            modelBuilder.Entity("RolePermissions", b =>
                {
                    b.Property<Guid>("PermissionGuid")
                        .HasColumnType("uuid");

                    b.Property<Guid>("RoleGuid")
                        .HasColumnType("uuid");

                    b.HasKey("PermissionGuid", "RoleGuid");

                    b.HasIndex("RoleGuid");

                    b.ToTable("RolePermissions");
                });

            modelBuilder.Entity("Identity.Domain.Entities.UserAggregate.User", b =>
                {
                    b.OwnsOne("Identity.Domain.ValueObjects.PhoneNumber", "PhoneNumber", b1 =>
                        {
                            b1.Property<Guid>("UserGuid")
                                .HasColumnType("uuid");

                            b1.Property<long>("AddressRegion")
                                .HasColumnType("bigint");

                            b1.Property<string>("PhoneCode")
                                .IsRequired()
                                .HasColumnType("text");

                            b1.HasKey("UserGuid");

                            b1.ToTable("User");

                            b1.WithOwner()
                                .HasForeignKey("UserGuid");
                        });

                    b.OwnsOne("Identity.Domain.ValueObjects.Address", "UserAddress", b1 =>
                        {
                            b1.Property<Guid>("UserGuid")
                                .HasColumnType("uuid");

                            b1.Property<string>("City")
                                .IsRequired()
                                .HasColumnType("text");

                            b1.Property<string>("Country")
                                .IsRequired()
                                .HasColumnType("text");

                            b1.Property<string>("Detail")
                                .IsRequired()
                                .HasColumnType("text");

                            b1.Property<string>("District")
                                .IsRequired()
                                .HasColumnType("text");

                            b1.Property<string>("Province")
                                .IsRequired()
                                .HasColumnType("text");

                            b1.Property<string>("Street")
                                .IsRequired()
                                .HasColumnType("text");

                            b1.HasKey("UserGuid");

                            b1.ToTable("User");

                            b1.WithOwner()
                                .HasForeignKey("UserGuid");
                        });

                    b.Navigation("PhoneNumber");

                    b.Navigation("UserAddress");
                });

            modelBuilder.Entity("Identity.Domain.Entities.UserAggregate.UserAccessFail", b =>
                {
                    b.HasOne("Identity.Domain.Entities.UserAggregate.User", null)
                        .WithOne("UserAccessFail")
                        .HasForeignKey("Identity.Domain.Entities.UserAggregate.UserAccessFail", "UserGuid")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Identity.Domain.Entities.UserAggregate.UserLoginHistory", b =>
                {
                    b.OwnsOne("Identity.Domain.ValueObjects.PhoneNumber", "PhoneNumber", b1 =>
                        {
                            b1.Property<Guid>("UserLoginHistoryLoginGuid")
                                .HasColumnType("uuid");

                            b1.Property<long>("AddressRegion")
                                .HasColumnType("bigint");

                            b1.Property<string>("PhoneCode")
                                .IsRequired()
                                .HasColumnType("text");

                            b1.HasKey("UserLoginHistoryLoginGuid");

                            b1.ToTable("UserLoginHistory");

                            b1.WithOwner()
                                .HasForeignKey("UserLoginHistoryLoginGuid");
                        });

                    b.Navigation("PhoneNumber")
                        .IsRequired();
                });

            modelBuilder.Entity("Identity.Domain.Entities.UserAggregate.UserSafety", b =>
                {
                    b.HasOne("Identity.Domain.Entities.UserAggregate.User", null)
                        .WithOne("UserSafety")
                        .HasForeignKey("Identity.Domain.Entities.UserAggregate.UserSafety", "UserGuid")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("RoleGroupPermissions", b =>
                {
                    b.HasOne("Identity.Domain.Entities.RoleAggregate.Permission", null)
                        .WithMany()
                        .HasForeignKey("PermissionGuid")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Identity.Domain.Entities.RoleAggregate.RoleGroup", null)
                        .WithMany()
                        .HasForeignKey("RoleGroupGuid")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("RolePermissions", b =>
                {
                    b.HasOne("Identity.Domain.Entities.RoleAggregate.Permission", null)
                        .WithMany()
                        .HasForeignKey("PermissionGuid")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Identity.Domain.Entities.RoleAggregate.Roles", null)
                        .WithMany()
                        .HasForeignKey("RoleGuid")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Identity.Domain.Entities.UserAggregate.User", b =>
                {
                    b.Navigation("UserAccessFail")
                        .IsRequired();

                    b.Navigation("UserSafety")
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
