// <auto-generated />
using System;
using Identity.Infrastructure.EntityFramework;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Identity.Infrastructure.Migrations
{
    [DbContext(typeof(UserDbContext))]
    partial class UserDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Identity.Domain.Entities.PhoneNumber", b =>
                {
                    b.Property<string>("PhoneCode")
                        .HasMaxLength(11)
                        .HasColumnType("character varying(11)");

                    b.Property<long>("AddressRegion")
                        .HasColumnType("bigint");

                    b.HasKey("PhoneCode");

                    b.ToTable("PhoneNumber");
                });

            modelBuilder.Entity("Identity.Domain.Entities.User", b =>
                {
                    b.Property<Guid>("UserGuid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int?>("BlackOrWhite")
                        .HasColumnType("integer");

                    b.Property<DateTime>("CreateDatetime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("UserAddress")
                        .HasColumnType("text");

                    b.Property<string>("UserEmail")
                        .HasColumnType("text");

                    b.Property<string>("UserName")
                        .HasColumnType("text");

                    b.Property<string>("UserPhonePhoneCode")
                        .HasColumnType("character varying(11)");

                    b.Property<Guid>("UserRoleGuid")
                        .HasColumnType("uuid");

                    b.HasKey("UserGuid");

                    b.HasIndex("UserPhonePhoneCode");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("Identity.Domain.Entities.UserAccessFail", b =>
                {
                    b.Property<Guid>("UserAccessFailGuid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("AccessFaildCount")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("LockOutEnd")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("UserGuid")
                        .HasColumnType("uuid");

                    b.HasKey("UserAccessFailGuid");

                    b.HasIndex("UserGuid")
                        .IsUnique();

                    b.ToTable("UserAccessFail");
                });

            modelBuilder.Entity("Identity.Domain.Entities.User", b =>
                {
                    b.HasOne("Identity.Domain.Entities.PhoneNumber", "UserPhone")
                        .WithMany()
                        .HasForeignKey("UserPhonePhoneCode");

                    b.Navigation("UserPhone");
                });

            modelBuilder.Entity("Identity.Domain.Entities.UserAccessFail", b =>
                {
                    b.HasOne("Identity.Domain.Entities.User", "User")
                        .WithOne("UserAccessFail")
                        .HasForeignKey("Identity.Domain.Entities.UserAccessFail", "UserGuid")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("Identity.Domain.Entities.User", b =>
                {
                    b.Navigation("UserAccessFail")
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
