// <auto-generated />
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Notcomd.Image.Server.Mapper;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Notcomd.Image.Server.Migrations
{
    [DbContext(typeof(Notcomd_Image_Module_DbContext))]
    partial class Notcomd_Image_Module_DbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Notcomd.Image.Server.Module.Notcomd_Image_Evaluate_Module", b =>
                {
                    b.Property<string>("Image_Ownership")
                        .HasColumnType("text");

                    b.Property<long>("Image_Level")
                        .HasColumnType("bigint");

                    b.Property<string>("Image_Size")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Image_Type")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Image_Ownership");

                    b.ToTable("Notcomd_Image_Evaluate_Module");
                });

            modelBuilder.Entity("Notcomd.Image.Server.Module.Notcomd_Image_Module", b =>
                {
                    b.Property<string>("Image_Url")
                        .HasColumnType("text");

                    b.Property<List<string>>("ImageTage")
                        .IsRequired()
                        .HasColumnType("text[]");

                    b.Property<DateTime>("Image_CreateTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Image_Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Image_Remake")
                        .IsRequired()
                        .HasColumnType("Text");

                    b.HasKey("Image_Url");

                    b.ToTable("Notcomd_Image_Table");
                });

            modelBuilder.Entity("Notcomd.Image.Server.Module.Notcomd_Image_Ownership_Module", b =>
                {
                    b.Property<string>("Image_Ownership_UserName")
                        .HasColumnType("text");

                    b.Property<bool>("Image_Privati")
                        .HasColumnType("boolean");

                    b.Property<string>("Image_User_HeadPort")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Image_Ownership_UserName");

                    b.ToTable("Notcomd_Image_Ownership_Module");
                });

            modelBuilder.Entity("Notcomd.Image.Server.Module.Notcomd_Image_Module", b =>
                {
                    b.HasOne("Notcomd.Image.Server.Module.Notcomd_Image_Evaluate_Module", "Notcomd_Image_Evaluate_Module")
                        .WithMany("Notcomd_Image_Module")
                        .HasForeignKey("Image_Url")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Notcomd.Image.Server.Module.Notcomd_Image_Ownership_Module", "Notcomd_Image_Ownership_Module")
                        .WithMany("Notcomd_Image_Module")
                        .HasForeignKey("Image_Url")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Notcomd_Image_Evaluate_Module");

                    b.Navigation("Notcomd_Image_Ownership_Module");
                });

            modelBuilder.Entity("Notcomd.Image.Server.Module.Notcomd_Image_Evaluate_Module", b =>
                {
                    b.Navigation("Notcomd_Image_Module");
                });

            modelBuilder.Entity("Notcomd.Image.Server.Module.Notcomd_Image_Ownership_Module", b =>
                {
                    b.Navigation("Notcomd_Image_Module");
                });
#pragma warning restore 612, 618
        }
    }
}
