<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net10.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="Microsoft.AspNetCore.Mvc.Core" Version="2.3.11"/>
        <PackageReference Include="Microsoft.EntityFrameworkCore" Version="10.0.9"/>
        <PackageReference Include="Microsoft.EntityFrameworkCore.Tools" Version="10.0.9">
            <PrivateAssets>all</PrivateAssets>
            <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
        </PackageReference>
        <PackageReference Include="Microsoft.Extensions.Logging.Abstractions" Version="10.0.9"/>
        <PackageReference Include="NotMediator" Version="1.0.5"/>
        <PackageReference Include="Npgsql.EntityFrameworkCore.PostgreSQL" Version="10.0.2"/>
    </ItemGroup>

    <ItemGroup>
        <ProjectReference Include="..\Video.Domain\Video.Domain.csproj"/>
        <ProjectReference Include="..\DomainInfrastructure\DomainInfrastructure.csproj"/>
    </ItemGroup>

</Project>