// <auto-generated />
using System;
using System.Collections.Generic;
using Message.Infrastructure.EntityFramework;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Message.Infrastructure.Migrations
{
    [DbContext(typeof(MessageDbContext))]
    [Migration("20260913173826_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Message.Domain.Entities.Announcement.Announcement", b =>
                {
                    b.Property<Guid>("AnnouncementGuid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasMaxLength(5000)
                        .HasColumnType("character varying(5000)");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("CreatorUserId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<bool>("IsRecalled")
                        .HasColumnType("boolean");

                    b.Property<DateTimeOffset?>("RecalledAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.HasKey("AnnouncementGuid");

                    b.HasIndex("CreatedAt");

                    b.HasIndex("IsRecalled", "CreatedAt");

                    b.ToTable("Announcements", (string)null);
                });

            modelBuilder.Entity("Message.Domain.Entities.Chat.ChatSession", b =>
                {
                    b.Property<Guid>("SessionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid?>("CircleId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("CreatorId")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("DismissedTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("GroupId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<bool>("IsDismissed")
                        .HasColumnType("boolean");

                    b.Property<string>("LastMessageContent")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<Guid?>("LastMessageId")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("LastMessageTime")
                        .HasColumnType("timestamp with time zone");

                    b.PrimitiveCollection<List<Guid>>("Participants")
                        .IsRequired()
                        .HasColumnType("uuid[]")
                        .HasColumnName("Participants");

                    b.Property<string>("SessionType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("SessionId");

                    b.HasIndex("CircleId")
                        .IsUnique()
                        .HasFilter("\"CircleId\" IS NOT NULL");

                    b.HasIndex("CreatorId");

                    b.HasIndex("GroupId")
                        .IsUnique()
                        .HasFilter("\"GroupId\" IS NOT NULL");

                    b.ToTable("ChatSessions", (string)null);
                });

            modelBuilder.Entity("Message.Domain.Entities.Chat.FileAttachment", b =>
                {
                    b.Property<Guid>("AttachmentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<int>("DownloadCount")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("DownloadTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("FileId")
                        .HasColumnType("uuid");

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<long>("FileSize")
                        .HasColumnType("bigint");

                    b.Property<string>("FileType")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("FileUri")
                        .IsRequired()
                        .HasMaxLength(2048)
                        .HasColumnType("character varying(2048)");

                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<Guid>("MessageId")
                        .HasColumnType("uuid");

                    b.Property<string>("MimeType")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("ThumbnailUri")
                        .HasMaxLength(2048)
                        .HasColumnType("character varying(2048)");

                    b.Property<DateTime>("UploadTime")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("AttachmentId");

                    b.HasIndex("FileId");

                    b.HasIndex("MessageId");

                    b.ToTable("FileAttachments", (string)null);
                });

            modelBuilder.Entity("Message.Domain.Entities.Chat.Message", b =>
                {
                    b.Property<Guid>("MessageId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("DeliveredTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<bool>("IsEncrypted")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsForwarded")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsRecalled")
                        .HasColumnType("boolean");

                    b.Property<Guid?>("OriginalMessageId")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("ReadTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("ReceiverId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("ReplyToMessageId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("SenderId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("SentTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("SessionId")
                        .HasColumnType("uuid");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("MessageId");

                    b.HasIndex("ReceiverId");

                    b.HasIndex("SenderId");

                    b.HasIndex("SentTime");

                    b.HasIndex("SessionId");

                    b.ToTable("Messages", (string)null);
                });

            modelBuilder.Entity("Message.Domain.Entities.Chat.MessageFriends", b =>
                {
                    b.Property<Guid>("FriendshipId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("AcceptedTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("CreatedTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("FriendGroupName")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<Guid>("FriendId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<bool>("IsMuted")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsStarred")
                        .HasColumnType("boolean");

                    b.Property<DateTime?>("LastInteractionTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Remark")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("FriendshipId");

                    b.HasIndex("FriendId");

                    b.HasIndex("UserId");

                    b.HasIndex("UserId", "FriendId")
                        .IsUnique();

                    b.ToTable("MessageFriends", (string)null);
                });

            modelBuilder.Entity("Message.Domain.Entities.Community.Circle", b =>
                {
                    b.Property<Guid>("CircleGuid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("AvatarUrl")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("CoverUrl")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<DateTimeOffset>("CreateTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<DateTimeOffset?>("DissolvedTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<int>("MaxMembers")
                        .HasColumnType("integer");

                    b.Property<int>("MemberCount")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<Guid>("OwnerGuid")
                        .HasColumnType("uuid");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("CircleGuid");

                    b.HasIndex("CreateTime")
                        .IsDescending();

                    b.HasIndex("OwnerGuid");

                    b.HasIndex("Status");

                    b.ToTable("Circles", (string)null);
                });

            modelBuilder.Entity("Message.Domain.Entities.Community.CircleInvitation", b =>
                {
                    b.Property<Guid>("InviteGuid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("CircleGuid")
                        .HasColumnType("uuid");

                    b.Property<string>("Code")
                        .HasMaxLength(6)
                        .HasColumnType("character varying(6)");

                    b.Property<DateTimeOffset>("CreateTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset>("ExpireTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("InviteeGuid")
                        .HasColumnType("uuid");

                    b.Property<Guid>("InviterGuid")
                        .HasColumnType("uuid");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid?>("Token")
                        .HasColumnType("uuid");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("InviteGuid");

                    b.HasIndex("CircleGuid");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.HasIndex("InviteeGuid");

                    b.HasIndex("Token")
                        .IsUnique();

                    b.ToTable("CircleInvitations", (string)null);
                });

            modelBuilder.Entity("Message.Domain.Entities.Community.CircleMember", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("CircleGuid")
                        .HasColumnType("uuid");

                    b.Property<Guid>("CircleMembleGuid")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("JoinTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Nickname")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("UserGuid")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("UserGuid");

                    b.HasIndex("CircleGuid", "UserGuid")
                        .IsUnique();

                    b.ToTable("CircleMembers", (string)null);
                });

            modelBuilder.Entity("Message.Domain.Entities.Community.Topic", b =>
                {
                    b.Property<Guid>("TopicGuid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreateTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("CreatorGuid")
                        .HasColumnType("uuid");

                    b.Property<string>("Description")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.Property<int>("PostCount")
                        .HasColumnType("integer");

                    b.HasKey("TopicGuid");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.HasIndex("PostCount")
                        .IsDescending();

                    b.ToTable("Topics", (string)null);
                });

            modelBuilder.Entity("Message.Domain.Entities.Community.UserFollow", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreateTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("FolloweeGuid")
                        .HasColumnType("uuid");

                    b.Property<Guid>("FollowerGuid")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("FolloweeGuid");

                    b.HasIndex("FollowerGuid", "FolloweeGuid")
                        .IsUnique();

                    b.ToTable("UserFollows", (string)null);
                });

            modelBuilder.Entity("Message.Domain.Entities.Group.Group", b =>
                {
                    b.Property<Guid>("GroupId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<bool>("AllowMemberEditInfo")
                        .HasColumnType("boolean");

                    b.Property<bool>("AllowMemberInvite")
                        .HasColumnType("boolean");

                    b.Property<string>("Avatar")
                        .HasColumnType("text");

                    b.Property<Guid?>("CircleId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<DateTime?>("DismissedTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("GroupName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<bool>("IsDismissed")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsPublic")
                        .HasColumnType("boolean");

                    b.Property<int>("MaxMembers")
                        .HasColumnType("integer");

                    b.Property<Guid>("OwnerId")
                        .HasColumnType("uuid");

                    b.HasKey("GroupId");

                    b.HasIndex("CircleId")
                        .IsUnique()
                        .HasFilter("\"CircleId\" IS NOT NULL");

                    b.HasIndex("IsPublic");

                    b.HasIndex("OwnerId");

                    b.ToTable("Groups", (string)null);
                });

            modelBuilder.Entity("Message.Domain.Entities.Group.GroupMember", b =>
                {
                    b.Property<Guid>("MemberId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("BannedTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("GroupId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<bool>("IsBanned")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsMuted")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("JoinTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("MuteEndTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Nickname")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("MemberId");

                    b.HasIndex("GroupId", "UserId")
                        .IsUnique();

                    b.ToTable("GroupMembers", (string)null);
                });

            modelBuilder.Entity("Message.Domain.Entities.Tweet.Comment", b =>
                {
                    b.Property<Guid>("CommentGuid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<DateTimeOffset>("CreateTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<int>("LikeCount")
                        .HasColumnType("integer");

                    b.Property<Guid?>("ParentGuid")
                        .HasColumnType("uuid");

                    b.Property<int>("ReplyCount")
                        .HasColumnType("integer");

                    b.Property<Guid?>("ReplyToGuid")
                        .HasColumnType("uuid");

                    b.Property<Guid>("TweetGuid")
                        .HasColumnType("uuid");

                    b.Property<Guid>("UserGuid")
                        .HasColumnType("uuid");

                    b.HasKey("CommentGuid");

                    b.HasIndex("ParentGuid");

                    b.HasIndex("UserGuid");

                    b.HasIndex("TweetGuid", "CreateTime");

                    b.ToTable("Comments", (string)null);
                });

            modelBuilder.Entity("Message.Domain.Entities.Tweet.Tweet", b =>
                {
                    b.Property<Guid>("TweetGuid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("AuditReason")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<Guid>("AuthorGuid")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("CircleGuid")
                        .HasColumnType("uuid");

                    b.Property<int>("CoinCount")
                        .HasColumnType("integer");

                    b.Property<int>("CommentCount")
                        .HasColumnType("integer");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<DateTimeOffset>("CreateTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("FavoriteCount")
                        .HasColumnType("integer");

                    b.Property<string>("Hashtags")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("Hashtags");

                    b.Property<long>("HotScore")
                        .HasColumnType("bigint");

                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<bool>("IsPinned")
                        .HasColumnType("boolean");

                    b.Property<int>("LikeCount")
                        .HasColumnType("integer");

                    b.Property<string>("LinkMetadata")
                        .HasColumnType("text");

                    b.Property<string>("Media")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("MediaUrls");

                    b.Property<DateTimeOffset?>("PublishTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("ShareCount")
                        .HasColumnType("integer");

                    b.Property<string>("TopicGuidsJson")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("TopicGuids");

                    b.Property<string>("TweetStatus")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("UpdateTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<long>("ViewCount")
                        .HasColumnType("bigint");

                    b.Property<string>("Visibility")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("TweetGuid");

                    b.HasIndex("AuthorGuid");

                    b.HasIndex("CircleGuid");

                    b.HasIndex("CreateTime")
                        .IsDescending();

                    b.HasIndex("Hashtags")
                        .IsDescending();

                    b.HasIndex("HotScore")
                        .IsDescending();

                    b.HasIndex("TweetStatus", "CreateTime")
                        .IsDescending(false, true);

                    b.ToTable("Tweets", (string)null);
                });

            modelBuilder.Entity("Message.Domain.Entities.Tweet.TweetAuditLog", b =>
                {
                    b.Property<Guid>("AuditGuid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("AuditTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("AuditorGuid")
                        .HasColumnType("uuid");

                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<string>("Reason")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<Guid>("TweetGuid")
                        .HasColumnType("uuid");

                    b.HasKey("AuditGuid");

                    b.HasIndex("AuditorGuid", "AuditTime")
                        .IsDescending(false, true);

                    b.HasIndex("TweetGuid", "AuditTime")
                        .IsDescending(false, true);

                    b.ToTable("TweetAuditLogs", (string)null);
                });

            modelBuilder.Entity("Message.Domain.Entities.Tweet.TweetInteraction", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreateTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("TweetGuid")
                        .HasColumnType("uuid");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("UserGuid")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("TweetGuid");

                    b.HasIndex("UserGuid");

                    b.HasIndex("TweetGuid", "UserGuid", "Type")
                        .IsUnique();

                    b.ToTable("TweetInteractions", (string)null);
                });

            modelBuilder.Entity("Message.Domain.Entities.Tweet.TweetNotification", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<DateTimeOffset>("CreateTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsRead")
                        .HasColumnType("boolean");

                    b.Property<Guid?>("RefGuid")
                        .HasColumnType("uuid");

                    b.Property<string>("RefType")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("UserGuid")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("Type");

                    b.HasIndex("UserGuid", "IsRead", "CreateTime")
                        .IsDescending(false, false, true);

                    b.ToTable("TweetNotifications", (string)null);
                });

            modelBuilder.Entity("Message.Domain.Entities.Tweet.TweetReport", b =>
                {
                    b.Property<Guid>("ReportGuid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("CreateTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<string>("ReportReason")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<Guid>("ReportedUserGuid")
                        .HasColumnType("uuid");

                    b.Property<Guid>("ReporterGuid")
                        .HasColumnType("uuid");

                    b.Property<string>("ReviewNote")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<DateTimeOffset?>("ReviewTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("ReviewerGuid")
                        .HasColumnType("uuid");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("TargetGuid")
                        .HasColumnType("uuid");

                    b.Property<string>("TargetType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("_evidenceUrls")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("EvidenceUrls");

                    b.HasKey("ReportGuid");

                    b.HasIndex("ReporterGuid");

                    b.HasIndex("Status", "CreateTime");

                    b.HasIndex("TargetType", "TargetGuid");

                    b.ToTable("TweetReports", (string)null);
                });

            modelBuilder.Entity("Message.Domain.Entities.User.UserInfo", b =>
                {
                    b.Property<Guid>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("AvatarUrl")
                        .HasColumnType("text");

                    b.Property<string>("BackgroundCoverUrl")
                        .HasMaxLength(2048)
                        .HasColumnType("character varying(2048)");

                    b.Property<string>("Bio")
                        .HasColumnType("text");

                    b.Property<long>("Coins")
                        .HasColumnType("bigint");

                    b.Property<DateTimeOffset>("CreateTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<long>("Experience")
                        .HasColumnType("bigint");

                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<int>("Level")
                        .HasColumnType("integer");

                    b.Property<string>("NickName")
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("UpdateTime")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("UserId");

                    b.HasIndex("Email");

                    b.ToTable("UserInfos", (string)null);
                });

            modelBuilder.Entity("Message.Domain.Entities.User.UserSignIn", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreateTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateOnly>("SignInDate")
                        .HasColumnType("date");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.HasIndex("UserId", "SignInDate")
                        .IsUnique();

                    b.ToTable("UserSignIns", (string)null);
                });

            modelBuilder.Entity("Message.Domain.Entities.Chat.FileAttachment", b =>
                {
                    b.HasOne("Message.Domain.Entities.Chat.Message", null)
                        .WithMany("Attachments")
                        .HasForeignKey("MessageId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Message.Domain.Entities.Community.CircleMember", b =>
                {
                    b.HasOne("Message.Domain.Entities.Community.Circle", null)
                        .WithMany("Members")
                        .HasForeignKey("CircleGuid")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Message.Domain.Entities.Group.GroupMember", b =>
                {
                    b.HasOne("Message.Domain.Entities.Group.Group", null)
                        .WithMany("Members")
                        .HasForeignKey("GroupId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Message.Domain.Entities.Chat.Message", b =>
                {
                    b.Navigation("Attachments");
                });

            modelBuilder.Entity("Message.Domain.Entities.Community.Circle", b =>
                {
                    b.Navigation("Members");
                });

            modelBuilder.Entity("Message.Domain.Entities.Group.Group", b =>
                {
                    b.Navigation("Members");
                });
#pragma warning restore 612, 618
        }
    }
}
