<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
        <TargetFramework>net9.0</TargetFramework>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="NotMediator" Version="1.0.4" />
    </ItemGroup>

    <ItemGroup>
        <ProjectReference Include="..\DomainCommonst\DomainCommonst.csproj" />
        <ProjectReference Include="..\JWToken\Token.JWT.csproj" />
    </ItemGroup>

</Project>
