<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
        <TargetFramework>net10.0</TargetFramework>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="Microsoft.AspNetCore.Mvc.Core" Version="2.3.11"/>
        <PackageReference Include="NotMediator" Version="1.0.5" />
    </ItemGroup>

    <ItemGroup>
        <ProjectReference Include="..\DomainCommons\DomainCommons.csproj"/>
        <ProjectReference Include="..\JWToken\Token.JWT.csproj"/>
    </ItemGroup>

</Project>
