<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
        <TargetFramework>net10.0</TargetFramework>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="NotMediator" Version="1.0.6" />
    </ItemGroup>

    <ItemGroup>
        <ProjectReference Include="..\Commons\Commons.csproj" />
        <ProjectReference Include="..\JWToken\JWToken.csproj" />
    </ItemGroup>

</Project>
