
<Project Sdk="Microsoft.NET.Sdk">
    <PropertyGroup>
        <TargetFramework>net10.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
        <RootNamespace>Notcomd.Token.JWT</RootNamespace>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="Microsoft.AspNetCore.Authentication.JwtBearer" Version="*"/>
        <PackageReference Include="Microsoft.AspNetCore.Mvc.Core" Version="2.3.11"/>
        <PackageReference Include="System.IdentityModel.Tokens.Jwt" Version="*"/>
    </ItemGroup>

</Project>
