// <auto-generated />
using System;
using Markdown.Infrastructure.EntityFramework;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Markdown.Infrastructure.Migrations
{
    [DbContext(typeof(MarkDownDbContext))]
    [Migration("20260913174024_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.HasSequence("MarkDocumentLikeGuid")
                .IncrementsBy(10);

            modelBuilder.HasSequence("MarkDownGuid")
                .IncrementsBy(10);

            modelBuilder.HasSequence("MarkFavoriteGuid")
                .IncrementsBy(10);

            modelBuilder.HasSequence("MarkReviewDislikeGuid")
                .IncrementsBy(10);

            modelBuilder.HasSequence("MarkReviewLikeGuid")
                .IncrementsBy(10);

            modelBuilder.Entity("Markdown.Domain.Entities.MarkCoin", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<long>("Amount")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasDefaultValue(0L);

                    b.Property<DateTimeOffset>("CreateAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("MarkCoinGuid")
                        .HasColumnType("uuid");

                    b.Property<Guid>("MarkDownGuid")
                        .HasColumnType("uuid");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("MarkDownGuid");

                    b.HasIndex("MarkDownGuid", "UserId")
                        .IsUnique();

                    b.ToTable("MarkCoin", (string)null);
                });

            modelBuilder.Entity("Markdown.Domain.Entities.MarkDocumentLike", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseHiLo(b.Property<int>("Id"), "MarkDocumentLikeGuid");

                    b.Property<DateTimeOffset>("CreateAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("MarkDownGuid")
                        .HasColumnType("uuid");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("MarkDownGuid");

                    b.HasIndex("MarkDownGuid", "UserId")
                        .IsUnique();

                    b.ToTable("MarkDocumentLike", (string)null);
                });

            modelBuilder.Entity("Markdown.Domain.Entities.MarkDown", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseHiLo(b.Property<int>("Id"), "MarkDownGuid");

                    b.Property<string>("CoverUrl")
                        .HasMaxLength(2048)
                        .HasColumnType("character varying(2048)");

                    b.Property<DateTimeOffset>("CreateAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("FileExt")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<string>("FileId")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<long>("FileSize")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasDefaultValue(0L);

                    b.Property<string>("FileUri")
                        .IsRequired()
                        .HasMaxLength(1024)
                        .HasColumnType("character varying(1024)");

                    b.Property<bool>("IsDelete")
                        .HasColumnType("boolean");

                    b.Property<int>("MarkDownAuth")
                        .HasColumnType("integer");

                    b.Property<Guid>("MarkDownGuid")
                        .HasColumnType("uuid");

                    b.Property<string>("MarkDownHash")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<string>("MarkDownName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("MarkDownTagboard")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("MarkReviewGuid")
                        .HasColumnType("uuid");

                    b.Property<Guid>("MarkUserGuid")
                        .HasColumnType("uuid");

                    b.Property<int>("Status")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(15);

                    b.Property<DateTimeOffset>("UpdateAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.ToTable("MarkDown", (string)null);
                });

            modelBuilder.Entity("Markdown.Domain.Entities.MarkFavorite", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseHiLo(b.Property<int>("Id"), "MarkFavoriteGuid");

                    b.Property<DateTimeOffset>("CreateAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("MarkDownGuid")
                        .HasColumnType("uuid");

                    b.Property<Guid>("MarkFavoriteGuid")
                        .HasColumnType("uuid");

                    b.Property<string>("TagsJson")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("UserGuid")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("MarkDownGuid");

                    b.HasIndex("UserGuid");

                    b.HasIndex("UserGuid", "MarkDownGuid")
                        .IsUnique();

                    b.ToTable("MarkFavorite", (string)null);
                });

            modelBuilder.Entity("Markdown.Domain.Entities.MarkFavoriteTag", b =>
                {
                    b.Property<Guid>("MarkFavoriteTagGuid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreateAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset>("LastUsedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Tag")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<int>("UseCount")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0);

                    b.Property<Guid>("UserGuid")
                        .HasColumnType("uuid");

                    b.HasKey("MarkFavoriteTagGuid");

                    b.HasIndex("UserGuid");

                    b.HasIndex("UserGuid", "Tag")
                        .IsUnique();

                    b.ToTable("MarkFavoriteTag", (string)null);
                });

            modelBuilder.Entity("Markdown.Domain.Entities.MarkReview", b =>
                {
                    b.Property<Guid>("MarkDownGuid")
                        .HasColumnType("uuid");

                    b.Property<bool>("IsDelete")
                        .HasColumnType("boolean");

                    b.Property<Guid?>("MarkAggregateRootGuid")
                        .HasColumnType("uuid");

                    b.Property<int>("MarkReviewAuth")
                        .HasColumnType("integer");

                    b.Property<string>("MarkReviewContent")
                        .HasColumnType("text");

                    b.Property<Guid>("MarkReviewGuid")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("MarkReviewTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("MarkDownGuid");

                    b.HasIndex("MarkAggregateRootGuid");

                    b.HasIndex("MarkDownGuid");

                    b.HasIndex("UserId");

                    b.ToTable("MarkReview", (string)null);
                });

            modelBuilder.Entity("Markdown.Domain.Entities.MarkReviewDislike", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseHiLo(b.Property<int>("Id"), "MarkReviewDislikeGuid");

                    b.Property<DateTimeOffset>("CreateAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("MarkReviewGuid")
                        .HasColumnType("uuid");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("MarkReviewGuid");

                    b.HasIndex("MarkReviewGuid", "UserId")
                        .IsUnique();

                    b.ToTable("MarkReviewDislike", (string)null);
                });

            modelBuilder.Entity("Markdown.Domain.Entities.MarkReviewLike", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseHiLo(b.Property<int>("Id"), "MarkReviewLikeGuid");

                    b.Property<DateTimeOffset>("CreateAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("MarkReviewGuid")
                        .HasColumnType("uuid");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("MarkReviewGuid");

                    b.HasIndex("MarkReviewGuid", "UserId")
                        .IsUnique();

                    b.ToTable("MarkReviewLike", (string)null);
                });

            modelBuilder.Entity("Markdown.Domain.Entities.OldMarkDown", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("AuthType")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset>("CreateAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsDelete")
                        .HasColumnType("boolean");

                    b.Property<Guid>("MarkDownGuid")
                        .HasColumnType("uuid");

                    b.Property<string>("OldMarkDownContent")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("OldMarkDownGuid")
                        .HasColumnType("uuid");

                    b.Property<string>("OldMarkDownHash")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("UpdateAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("UserGuid")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("MarkDownGuid");

                    b.ToTable("OldMarkDown");
                });

            modelBuilder.Entity("Markdown.Infrastructure.Idempotent.ClientRequest", b =>
                {
                    b.Property<Guid>("ClientRequestId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("ClientRequestName")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<DateTimeOffset>("Created")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ResponseJson")
                        .HasColumnType("text");

                    b.HasKey("ClientRequestId");

                    b.ToTable("ClientRequest", (string)null);
                });

            modelBuilder.Entity("Markdown.Domain.Entities.MarkDown", b =>
                {
                    b.OwnsOne("Markdown.Domain.Entities.MarkQuote", "MarkQuote", b1 =>
                        {
                            b1.Property<int>("MarkDownId")
                                .HasColumnType("integer");

                            b1.Property<long>("CoinSome")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("bigint")
                                .HasDefaultValue(0L)
                                .HasColumnName("CoinCount");

                            b1.Property<long>("FavoriteSome")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("bigint")
                                .HasDefaultValue(0L)
                                .HasColumnName("FavoriteCount");

                            b1.Property<double>("HeatScore")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("double precision")
                                .HasDefaultValue(0.0)
                                .HasColumnName("HeatScore");

                            b1.Property<long>("LoveSome")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("bigint")
                                .HasDefaultValue(0L)
                                .HasColumnName("LoveCount");

                            b1.Property<long>("ShareSome")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("bigint")
                                .HasDefaultValue(0L)
                                .HasColumnName("ShareCount");

                            b1.Property<long>("ViewSome")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("bigint")
                                .HasDefaultValue(0L)
                                .HasColumnName("ViewCount");

                            b1.HasKey("MarkDownId");

                            b1.ToTable("MarkDown");

                            b1.WithOwner()
                                .HasForeignKey("MarkDownId");
                        });

                    b.Navigation("MarkQuote")
                        .IsRequired();
                });

            modelBuilder.Entity("Markdown.Domain.Entities.MarkReview", b =>
                {
                    b.HasOne("Markdown.Domain.Entities.MarkReview", null)
                        .WithMany("MarkReviews")
                        .HasForeignKey("MarkAggregateRootGuid")
                        .HasPrincipalKey("MarkReviewGuid")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Markdown.Domain.Entities.MarkDown", "MarkDown")
                        .WithMany("MarkReviews")
                        .HasForeignKey("MarkDownGuid")
                        .HasPrincipalKey("MarkDownGuid")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.OwnsMany("Markdown.Domain.Entities.ReviewImage", "ReviewImages", b1 =>
                        {
                            b1.Property<Guid>("MarkReviewMarkDownGuid");

                            b1.Property<int>("__synthesizedOrdinal")
                                .ValueGeneratedOnAdd();

                            b1.Property<string>("ImageName")
                                .IsRequired();

                            b1.Property<string>("ImageUrl")
                                .IsRequired();

                            b1.HasKey("MarkReviewMarkDownGuid", "__synthesizedOrdinal");

                            b1.ToTable("MarkReview");

                            b1
                                .ToJson("ReviewImages")
                                .HasColumnType("jsonb");

                            b1.WithOwner()
                                .HasForeignKey("MarkReviewMarkDownGuid");
                        });

                    b.OwnsOne("Markdown.Domain.Entities.ReviewQuote", "ReviewQuote", b1 =>
                        {
                            b1.Property<Guid>("MarkReviewMarkDownGuid")
                                .HasColumnType("uuid");

                            b1.Property<long>("DislikeSome")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("bigint")
                                .HasDefaultValue(0L)
                                .HasColumnName("DislikeCount");

                            b1.Property<long>("LoveSome")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("bigint")
                                .HasDefaultValue(0L)
                                .HasColumnName("LoveCount");

                            b1.Property<long>("ReplySome")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("bigint")
                                .HasDefaultValue(0L)
                                .HasColumnName("ReplyCount");

                            b1.Property<long>("ViewSome")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("bigint")
                                .HasDefaultValue(0L)
                                .HasColumnName("ViewCount");

                            b1.HasKey("MarkReviewMarkDownGuid");

                            b1.ToTable("MarkReview");

                            b1.WithOwner()
                                .HasForeignKey("MarkReviewMarkDownGuid");
                        });

                    b.Navigation("MarkDown");

                    b.Navigation("ReviewImages");

                    b.Navigation("ReviewQuote")
                        .IsRequired();
                });

            modelBuilder.Entity("Markdown.Domain.Entities.OldMarkDown", b =>
                {
                    b.HasOne("Markdown.Domain.Entities.MarkDown", "MarkDown")
                        .WithMany("OldMarkDowns")
                        .HasForeignKey("MarkDownGuid")
                        .HasPrincipalKey("MarkDownGuid")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("MarkDown");
                });

            modelBuilder.Entity("Markdown.Domain.Entities.MarkDown", b =>
                {
                    b.Navigation("MarkReviews");

                    b.Navigation("OldMarkDowns");
                });

            modelBuilder.Entity("Markdown.Domain.Entities.MarkReview", b =>
                {
                    b.Navigation("MarkReviews");
                });
#pragma warning restore 612, 618
        }
    }
}
