// <auto-generated />
using System;
using Markdown.Infrastructure.EntityFramework;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Markdown.Infrastructure.Migrations
{
    [DbContext(typeof(MarkDownDbContext))]
    partial class MarkDownDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.HasSequence("MarkDownGuid")
                .IncrementsBy(10);

            modelBuilder.HasSequence("MarkHistoryseq")
                .IncrementsBy(10);

            modelBuilder.HasSequence("MarkReviewGuid")
                .IncrementsBy(10);

            modelBuilder.HasSequence("ReviewImageGuid")
                .IncrementsBy(10);

            modelBuilder.Entity("Markdown.Domain.Entities.MarkDown", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseHiLo(b.Property<int>("Id"), "MarkDownGuid");

                    b.Property<DateTimeOffset>("CreateAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsDelete")
                        .HasColumnType("boolean");

                    b.Property<int>("MarkDownAuth")
                        .HasColumnType("integer");

                    b.Property<string>("MarkDownContent")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("MarkDownGuid")
                        .HasColumnType("uuid");

                    b.Property<string>("MarkDownHash")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("MarkDownName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("MarkDownTagboard")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("MarkOption")
                        .HasColumnType("integer");

                    b.Property<Guid>("MarkReviewGuid")
                        .HasColumnType("uuid");

                    b.Property<Guid>("MarkUserGuid")
                        .HasColumnType("uuid");

                    b.Property<int>("Status")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(17);

                    b.Property<DateTimeOffset>("UpdateAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.ToTable("MarkDown", (string)null);
                });

            modelBuilder.Entity("Markdown.Domain.Entities.MarkHistory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseHiLo(b.Property<int>("Id"), "MarkHistoryseq");

                    b.Property<DateTimeOffset>("LastReadTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("MarkDownGuid")
                        .HasColumnType("uuid");

                    b.Property<int?>("MarkDownId")
                        .HasColumnType("integer");

                    b.Property<Guid>("MarkHistoryGuid")
                        .HasColumnType("uuid");

                    b.Property<string>("Note")
                        .HasColumnType("text");

                    b.Property<int>("ReadCount")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset>("ReadTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("ReadingProgress")
                        .HasColumnType("integer");

                    b.Property<Guid>("UserGuid")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("MarkDownId");

                    b.ToTable("MarkHistory", (string)null);
                });

            modelBuilder.Entity("Markdown.Domain.Entities.MarkReview", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseHiLo(b.Property<int>("Id"), "MarkReviewGuid");

                    b.Property<bool>("IsDelete")
                        .HasColumnType("boolean");

                    b.Property<Guid?>("MarkAggregateRootGuid")
                        .HasColumnType("uuid");

                    b.Property<Guid>("MarkDownGuid")
                        .HasColumnType("uuid");

                    b.Property<int>("MarkReviewAuth")
                        .HasColumnType("integer");

                    b.Property<string>("MarkReviewContent")
                        .HasColumnType("text");

                    b.Property<Guid>("MarkReviewGuid")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("MarkReviewTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("MarkAggregateRootGuid");

                    b.HasIndex("MarkDownGuid");

                    b.HasIndex("UserId");

                    b.ToTable("MarkReview", (string)null);
                });

            modelBuilder.Entity("Markdown.Domain.Entities.OldMarkDown", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTimeOffset>("CreateAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsDelete")
                        .HasColumnType("boolean");

                    b.Property<Guid>("MarkDownGuid")
                        .HasColumnType("uuid");

                    b.Property<string>("OldMarkDownContent")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("OldMarkDownGuid")
                        .HasColumnType("uuid");

                    b.Property<string>("OldMarkDownHash")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset>("UpdateAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("UserGuid")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("MarkDownGuid");

                    b.ToTable("OldMarkDown");
                });

            modelBuilder.Entity("Markdown.Domain.Entities.ReviewImage", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseHiLo(b.Property<int>("Id"), "ReviewImageGuid");

                    b.Property<string>("ImageName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("MarkReviewId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("MarkReviewId");

                    b.ToTable("ReviewImage", (string)null);
                });

            modelBuilder.Entity("Markdown.Infrastructure.Idempotent.ClientRequest", b =>
                {
                    b.Property<Guid>("ClientRequestId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("ClientRequestName")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<DateTimeOffset>("Created")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("ClientRequestId");

                    b.ToTable("ClientRequest", (string)null);
                });

            modelBuilder.Entity("Markdown.Domain.Entities.MarkHistory", b =>
                {
                    b.HasOne("Markdown.Domain.Entities.MarkDown", "MarkDown")
                        .WithMany()
                        .HasForeignKey("MarkDownId");

                    b.Navigation("MarkDown");
                });

            modelBuilder.Entity("Markdown.Domain.Entities.MarkReview", b =>
                {
                    b.HasOne("Markdown.Domain.Entities.MarkReview", null)
                        .WithMany("MarkReviews")
                        .HasForeignKey("MarkAggregateRootGuid")
                        .HasPrincipalKey("MarkReviewGuid")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Markdown.Domain.Entities.MarkDown", "MarkDown")
                        .WithMany("MarkReviews")
                        .HasForeignKey("MarkDownGuid")
                        .HasPrincipalKey("MarkDownGuid")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.OwnsOne("Markdown.Domain.Entities.MarkQuote", "MarkQuote", b1 =>
                        {
                            b1.Property<int>("MarkReviewId")
                                .HasColumnType("integer");

                            b1.Property<long>("CommentSome")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("bigint")
                                .HasDefaultValue(0L)
                                .HasColumnName("CommentCount");

                            b1.Property<long>("LoveSome")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("bigint")
                                .HasDefaultValue(0L)
                                .HasColumnName("LoveCount");

                            b1.Property<long>("ReviewSome")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("bigint")
                                .HasDefaultValue(0L)
                                .HasColumnName("ReplyCount");

                            b1.Property<long>("ShareSome")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("bigint")
                                .HasDefaultValue(0L)
                                .HasColumnName("ShareCount");

                            b1.Property<long>("ViewSome")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("bigint")
                                .HasDefaultValue(0L)
                                .HasColumnName("ViewCount");

                            b1.HasKey("MarkReviewId");

                            b1.ToTable("MarkReview");

                            b1.WithOwner()
                                .HasForeignKey("MarkReviewId");
                        });

                    b.Navigation("MarkDown");

                    b.Navigation("MarkQuote")
                        .IsRequired();
                });

            modelBuilder.Entity("Markdown.Domain.Entities.OldMarkDown", b =>
                {
                    b.HasOne("Markdown.Domain.Entities.MarkDown", "MarkDown")
                        .WithMany("OldMarkDowns")
                        .HasForeignKey("MarkDownGuid")
                        .HasPrincipalKey("MarkDownGuid")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("MarkDown");
                });

            modelBuilder.Entity("Markdown.Domain.Entities.ReviewImage", b =>
                {
                    b.HasOne("Markdown.Domain.Entities.MarkReview", "MarkReview")
                        .WithMany("ReviewImages")
                        .HasForeignKey("MarkReviewId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("MarkReview");
                });

            modelBuilder.Entity("Markdown.Domain.Entities.MarkDown", b =>
                {
                    b.Navigation("MarkReviews");

                    b.Navigation("OldMarkDowns");
                });

            modelBuilder.Entity("Markdown.Domain.Entities.MarkReview", b =>
                {
                    b.Navigation("MarkReviews");

                    b.Navigation("ReviewImages");
                });
#pragma warning restore 612, 618
        }
    }
}
